### ISSUE TITLE
Metrics after each run

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#10]
We should be getting automated metrics from this as well. We should collect:

* Number of issues in each state
* Average open time?

...and put into a spreadsheet somewhere. 

This is probably best for when it's fully automated.

**Comment by jctanner** [comment]
I think the data described with this request is already collected here https://jctanner.github.io/

Here's the sourcecode ... https://github.com/jctanner/pr-triage/blob/master/WORKFLOW.sh
