### ISSUE TITLE
[tests] mock ansible-doc / repository content

### ISSUE THREAD

**Issue by pilou-** [ansible/ansibullbot#1015]
Following #1002.

Tests rely on `BOTMETA.yml` from devel branch. This isn't ideal because updates of `BOTMETA.yml` from ansible repository might break ansibullbot tests.

One of these should be mocked:
- either `ansible-doc` command
- or ansible repository content

In first case, an integration test must be added in order to check that ansibullbot is able to call `ansible-doc`, in order to avoid problem like db0db84020265fba1aba5bae9c147d13e6aa6f31.

**Comment by gundalow** [comment]
Is this "just" :tm: a case of having a sample `BOTMETA.yml` included in the `ansibullbot` repo for testing purposes?

**Comment by pilou-** [comment]
This isn't about `BOTMETA.yml`, this is about the `ansible-doc` command called by ansibullbot ([here](https://github.com/ansible/ansibullbot/blob/aa4d423a8fd6d41fd2e3012c6468b820532f4368/ansibullbot/utils/component_tools.py#L168)).

**Comment by mkrizek** [comment]
The call to `ansible-doc` is being removed in https://github.com/ansible/ansibullbot/pull/1515.
