### ISSUE TITLE
Bot should post a useful comment once it detects a PR with missing repo/branch

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansibullbot#1018]
I expect that i'd post somethig like https://github.com/ansible/ansible/pull/40411#issuecomment-418708959 if check like #1017 met.

**Comment by webknjaz** [comment]
N.B. It was suggested by @jctanner in Slack that it should also be closed. But I still insist on posting a message along with that.

**Comment by jctanner** [comment]
Yep, the closure message can indicate why it was closed.

**Comment by jctanner** [comment]
@gundalow thoughts?

**Comment by gundalow** [comment]
+1 to closing with message
