### ISSUE TITLE
Teach bot about release managers

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansibullbot#1024]
I think bot should ping RMs when backports to their branches are submitted. I'm a bit tired looking up for who is the RM for which release to forward those PRs to them.
Logic should be pretty simple (pseudo code):
```python
rms_map = {  # this should reside in BOTMETA
  (2, 7): @...,
}

num_releases_supported = 4

current_release = 2, 7

minumum_supported_release = current_release - num_releases_supported

pr_target_branch_version = ...

if pr_target_branch_version < minumum_supported_release:
    post_eol_msg()
    close_pr()

rm = rms_map.get(pr_target_branch_version)
post_notification_in_pr(release_manager=rm)
# optionally
set_as_pr_reviewer(rm)
```
(also related: #929)

**Comment by gundalow** [comment]
1) I've asked the release managers if they want this
2) Need to understand *why* people need to know who the RM is
If releases are happening every two weeks then we should just "trust" that PRs will get merged
3) RM's are currently defined in the ROADMAP's


General note, in GitHub you can search for `is:pr is:open base:stable-2.6`

**Comment by webknjaz** [comment]
It's more of a triaging burden. I keep forgetting where to look up the data and it doesn't stick in my memory. So for RMs, for example, I tend to use search in Slack to find a message where @abadger texted a list of RMs.
It's completely automatable. What is the point of human triaging backports, when bot could do the same (and untriage that)?

**Comment by gundalow** [comment]
Need RM's input though I think for triage we can just ignore `backports`.

I *thought* the process was that RMs would review the list of open PRs and merge every so often,

Or put another way I'd like to clarify what the correct workflow is *before* we code things.

If RMs do want assigning then this would be great and thanks for the code

**Comment by abadger** [comment]
this is currently not needed as the Release Manager procedure relies on searching for all PRs against the stable-X.Y branches.  Explicit CC on all tickets doesn't add to that.

Explicit CC on selected tickets which are seen as intrusive or controversial to merge could be useful but that is not nearly as easy to automate as what is proposed.

Note that to solve the triage burden, remove the need to ping a specific RM from the triage routine.

**Comment by mattclay** [comment]
Release managers should not normally be pinged about backports manually or automatically. Doing so creates noise for release managers, as they already review all backports against their branches as part of the release process.

If there is something unusual or questionable about a backport that should be immediately addressed, then a ping to the RM may be warranted.

**Comment by webknjaz** [comment]
It seems like another instance of abusing `needs_triage` label then

**Comment by mattclay** [comment]
I don't think backports need to be included in triage, since the RMs already handle them.

**Comment by webknjaz** [comment]
@mattclay so autountriaging (#990) is fine in this case?

**Comment by gundalow** [comment]
As agreed by Release Managers, they do NOT wish to be notified, they use GitHub searches.

Therefore closing
