### ISSUE TITLE
Bot making "bad PR" comments multiple times

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#1037]
The bot is making "bad PR" comments on the same PR multiple times:

https://github.com/ansible/ansible/pull/45859#issuecomment-422960456
https://github.com/ansible/ansible/pull/45805#issuecomment-422940174

**Comment by dagwieers** [comment]
Yup, and we shouldn't make any judgement calls about PR's being "bad" :-)

**Comment by mkrizek** [comment]
Hrm, @pilou- looks like https://github.com/ansible/ansibullbot/pull/1035 didn't fix this completely?

**Comment by pilou-** [comment]
I am not able to reproduce it using that command:

> ./triage_ansible.py --dry-run --pr 45859 --log log --ignore_bot_broken --ignore_state

I checked the current bot version ([here](http://ansibullbot.eng.ansible.com/cgi-bin/ansibot_status.cgi), last version is used). I guess i am missing something ?!?

**Comment by mkrizek** [comment]
Yeah, I can't reproduce it either. Maybe it's tied to a specific state of the PR? I'll try to reproduce the issue in a unit test.

**Comment by gundalow** [comment]
Another example https://github.com/ansible/ansible/pull/45805

Can we also add a label to these issues & PRs so I can keep an eye on them as not everyone will join IRC or know how to ask for help.

I've asked the Docs Team to come up with some nicer wording

**Comment by mkrizek** [comment]
> Another example ansible/ansible#45805

Already in the original issue description.

> Can we also add a label to these issues & PRs so I can keep an eye on them as not everyone will join IRC or know how to ask for help.

What label would that be?

> I've asked the Docs Team to come up with some nicer wording

+1. Thanks!

**Comment by gundalow** [comment]
lets use "potentially problematic" rather than bad
label `bad_pr` as that's what people know it as

**Comment by dagwieers** [comment]
I'd go for `large_pr` if it contains more than 50 files, and something else for a PR with merge commits, maybe `incorrect_pr` or something better.

**Comment by gundalow** [comment]
Improved the wording in https://github.com/ansible/ansibullbot/commit/1d6b87ca4611dac46f95b3be27864f12cd302d7f

Although multiple labels could be useful I think the end result is the same, a human needs to look into it

**Comment by dagwieers** [comment]
It is not the same.

If the PR has merge commits, the user can fix it themselves (or may need help fixing it themselves). The PR could be against the wrong branch, or he did something wrong in Git.

If the PR has a lot of files, that's not really a problem. I don't really understand why we think this is a problem, unless it has merge commits. We can't assume that it has merge commits because it has a lot of files.

So either remove that selector, or do something useful with it. But it shouldn't give the same error message. Or you will confuse users with the wrong assessment or the wrong resolution.

**Comment by gundalow** [comment]
I think merge_commits already has a label, and I didn't think triggered `bad_pr`

**Comment by dagwieers** [comment]
Hmm, then what is considered a bad PR ? Just more than 50 files ? Call it `large_pr`.
But why are we labeling Large PRs ? Is it to avoid auto-merge ? I don't think auto-merge would work if the author doesn't have ownership of those 50 files, but if he does, what would be the issue ?

So I think we need to clarify what the purpose is...

**Comment by gundalow** [comment]
OK, so let's break this down

* ~Improve wording (no use of `bad`)~ - DONE
* Fix to avoid double posting - As seen on Dag's PR
* Clarify workflow - after AnsibleFest

**Comment by mattclay** [comment]
I believe detection of large PRs was intended as a simple way of identifying PRs that were likely incorrectly created or rebased, and thus included changes to many files beyond what the contributor intended.

**Comment by gundalow** [comment]
Yup, to avoid incorrectly `@mentioning` spam and adding loads of labels
