### ISSUE TITLE
How does it identifies abandoned issues/modules?

### ISSUE THREAD

**Issue by techtonik** [ansible/ansibullbot#1040]
Continuing questions (see #1039)  about `ansibullbot` docs:

1. How does it identifies abandoned issues?
2. How does it identifies missing maintainers?
3. Is there a list of status? If not, is there a way to fetch the data (for specific module)?

**Comment by techtonik** [comment]
1. Well, [Overview](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#overview) says that it identifies issues that are abandoned.
2. I mean abandoned as in the overview above:
>   Identifies modules abandoned by their maintainers so that we can find new maintainers;
3. "status" is again from the overview:
> Tracks the current status of pull requests;

In particular, I am interested to see the dashboard with some queues - PR queue sorted by votes, issues that are "abandoned/missing" and all kind of pending queues that are requiring human intervention.

**Comment by jctanner** [comment]
Ah, okay ... yeah that information isn't completely correct. I did intend to make the bot perform the check for abandonment, but never got around to it.

I've not implemented a dashboard. All data is computed in memory and stored on disk as json for each individual issue.

**Comment by techtonik** [comment]
JSON is good. As soon as there is some public website for those, I am sure people will send pull requests to improve "the dashboard".

**Comment by gundalow** [comment]
Anything left here, if so please reopen
