### ISSUE TITLE
botmeta schema validator should be part of the ansibot deployment

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1041]
https://github.com/ansible/ansibullbot/tree/master/botmeta_schema_validator

I'd like botmeta.eng.ansible.com to point at the ansibot.eng.ansible.com instance and route traffic into a container or set of containers on that host.

**Comment by mkrizek** [comment]
@mattclay do you think we can put the `botmeta_schema_validator` docker image to our `quay.io`?

**Comment by mattclay** [comment]
@mkrizek We can. What's the use case and/or workflow going to look like?

**Comment by samdoran** [comment]
I'm thinking we would have an automated build watching [this repo](
https://github.com/ansible/ansibullbot/tree/master/botmeta_schema_validator). Quay can then issue a webhook post to Tower when new images are built to deploy the new image.

**Comment by jctanner** [comment]
done
