### ISSUE TITLE
PRs incorrectly marked as support:core

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1042]
https://github.com/ansible/ansible/pull/44938#event-1853681314
`ANSIBLE_METADATA` and BOTMETA shows this should be `support:community`

**Comment by webknjaz** [comment]
https://github.com/ansible/ansible/pull/46037/files#diff-f06279bc4bd5b939c4066292a7825384L23 (it's not clear whether it should be marked both core and community)

**Comment by webknjaz** [comment]
https://github.com/ansible/ansible/pull/46038 (marked both core+community, should it behave like this?)
