### ISSUE TITLE
ansibot adds "thank you for submitting this pull-request !" for issues

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansibullbot#1059]
It really shouldn't do that for issues :)

Also, there's a [superfluous space](https://english.stackexchange.com/a/4646) before the exclamation mark.

**Comment by felixfontein** [comment]
Example: https://github.com/ansible/ansible/issues/45683#issuecomment-427865363

**Comment by felixfontein** [comment]
CC @pilou-

**Comment by pilou-** [comment]
@felixfontein thanks for pointing that :) !
