### ISSUE TITLE
KeyError: 0 in self._pr_reviews[idx][u'commit_id'] = None

### ISSUE THREAD

**Issue by mkrizek** [ansible/ansibullbot#1068]
This started appearing sometime after py3 support has been merged: 

```
2018-10-09 06:44:15,710 INFO starting triage for https://github.com/ansible/ansible/pull/46648
Traceback (most recent call last):
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 42, in 
    main()
  File "/home/ansibot/ansibullbot/triage_ansible.py", line 38, in main
    AnsibleTriage().start()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 184, in start
    self.loop()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/defaulttriager.py", line 295, in loop
    self.run()
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 457, in run
    self.build_history(iw)
  File "/home/ansibot/ansibullbot/ansibullbot/triagers/ansible.py", line 2042, in build_history
    iw.history.merge_reviews(iw.reviews)
  File "/home/ansibot/ansibullbot/ansibullbot/wrappers/defaultwrapper.py", line 1077, in reviews
    self._pr_reviews[idx][u'commit_id'] = None
KeyError: 0
```

May not be directly related, might just revealed it.

cc @webknjaz

**Comment by webknjaz** [comment]
A few things to consider:

`get_reviews` function has `if isinstance(jdata, dict)` in it implying that it might be not `dict`, but something else.

`if self._pr_reviews is False:` in `reviews` property implies that it might be a `bool` as well.

`for idx, x in enumerate(self._pr_reviews):` suggests that it's most likely a sequence (I'd say list/set/tuple).

This all above drives me crazy: it's not a good design when a var can hold a bunch of different data types throughout the runtime.

Also `enumerate()` would emit tuples with valid indices and values for list, but it'd emit number+key tuples for dict. Obviously, when iterating `dict` it'd expect keys, not order numbers there, when referencing items.


I think my changes didn't affect this snippet at all. I also think this needs a heavy refactoring.

**Comment by webknjaz** [comment]
Just checked the diff in PR: the only thing was turning keys into unicode literals

**Comment by webknjaz** [comment]
I think, the original author meant to iterate over items of dict.

**Comment by webknjaz** [comment]
OTOH pr_reviews must be a list. so why it's a dict in runtime?

**Comment by webknjaz** [comment]
It looks like rate limiting guard expression is wrong. According to https://developer.github.com/v3/#rate-limiting, when rate limited one would receive
```json
{
   "message": "API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
   "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

but `u'rate' in jdata` would be always false if done against dict, not a string. the correct thing to do will be `u'rate' in ORIGINAL_JSON_STRING` or `u'rate' in jdata[u'message']`.

I, however, would recommend relying on HTTP response code first and then checking for details. It's also available as `X-RateLimit-Remaining: 0` header.
