### ISSUE TITLE
Ansibot added an extraneous shipit

### ISSUE THREAD

**Issue by pilou-** [ansible/ansibullbot#1080]
Here: https://github.com/ansible/ansible/pull/46137#issuecomment-427588406

```
test/integration/targets/docker_network/aliases
support: community
maintainers: chouseknecht keitwb olsaki

test/integration/targets/docker_network/meta/main.yml
support: community
maintainers: chouseknecht keitwb olsaki

test/integration/targets/docker_network/tasks/main.yml
support: community
maintainers: chouseknecht keitwb olsaki

test/integration/targets/docker_network/tasks/run-test.yml
support: community
maintainers: chouseknecht keitwb olsaki

test/integration/targets/docker_network/tasks/tests/basic.yml
support: community
maintainers: chouseknecht keitwb olsaki
[...]
maintainer_shipits (module maintainers): 0
community_shipits (namespace maintainers): 0
ansible_shipits (core team members): 1
shipit_actors (maintainers or core team members): felixfontein
shipit_actors_other: pilou-
```

felixfontein is the submitter but he is neither a maintainer (he is not listed in the maintainers of updated files) nor a core team member (he doesn't belong to `ansible-commit` or `ansible-community` GitHub teams). Then the bot should not detect an `ansible_shipits`.

I am not able to reproduce this one locally. Note that because I am not a member of the Ansible organization, I am not able to run Ansibullbot without this patch:
```
diff --git a/ansibullbot/triagers/ansible.py b/ansibullbot/triagers/ansible.py
index 1686a73..7139701 100644
--- a/ansibullbot/triagers/ansible.py
+++ b/ansibullbot/triagers/ansible.py
@@ -267,6 +267,15 @@ class AnsibleTriage(DefaultTriager):
 
     @property
     def ansible_core_team(self):
+        return ['jimi-c', 'bcoca', 'nitzmahone', 'abadger', 'mckerrj',
+                'robynbergeron', 'gregdek', 'emonty', 'sivel', 'qalthos',
+                'jctanner', 'privateip', 'amenonsen', 'mscherer', 'resmo',
+                'Shrews', 'docschick', 'ghjm', 'chouseknecht', 'trondhindenes',
+                'jhawkesworth', 'willthames', 'ryansb', 'alikins', 'dagwieers',
+                'caphrim007', 's-hertel', 'samdoran', 'dharmabumstead',
+                'mattclay', 'mkrizek', 'kedarX', 'ganeshrn', 'trishnaguha',
+                'agaffney']
+
         if not self._ansible_core_team:
             teams = [
                 u'ansible-commit',
```

**Comment by webknjaz** [comment]
I think it comes from bot meta: https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L106

**Comment by pilou-** [comment]
related code is here: https://github.com/ansible/ansibullbot/blob/2be4cccc746bd8fa4382b8fcdedffb369bd82322/ansibullbot/triagers/plugins/shipit.py#L303

> I think it comes from bot meta: https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml#L106

If that were the case, how could a maintainer listed as a core team member (`ansible_shipits (core team members): 1`) ?

**Comment by webknjaz** [comment]
That's a good question. Do you think you could submit a test for that?

**Comment by felixfontein** [comment]
Also, I'm just on the notify list, I'm not even a "proper" maintainer :)

**Comment by pilou-** [comment]
Same thing here (felixfontein shipit accounted as core team shipit):
https://github.com/ansible/ansible/pull/35370
https://github.com/ansible/ansible/pull/47247

**Comment by mkrizek** [comment]
Core team members is anyone from any of these teams:
https://github.com/ansible/ansibullbot/blob/4cf6b17aace86091ca08c626fefe7bd8a9e5a8fd/ansibullbot/triagers/ansible.py#L311-L313

Since @felixfontein is now in `ansible-community`, the fact that he would be in `ansible_shipits` is now expected. I am going to go ahead and close this.
