### ISSUE TITLE
premature removal of needs_triage when no maintainers

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1084]
https://github.com/ansible/ansibullbot/blob/master/ansibullbot/wrappers/historywrapper.py#L146-L159

```
    def _find_events_by_actor(self, eventname, actor, maxcount=1):
        matching_events = []
        for event in self.history:
            if event[u'event'] == eventname or not eventname:
                # allow actor to be a list or a string
                if type(actor) != list and event[u'actor'] == actor:
                    matching_events.append(event)
                elif type(actor) == list and event[u'actor'] in actor:
                    matching_events.append(event)
                elif not actor:
                    matching_events.append(event)
                if len(matching_events) == maxcount:
                    break
        return matching_events
```

This leads to the potential situation where a component has no maintainer, and the triage facts function gets a `True` back from historywrapper.has_labeled, historywrapper.has_unabeled, historywrapper.has_reviewed. Commenting out the `elif not actor` block fixes it in local testing, but the code needs better review and unit testing.

**Comment by mkrizek** [comment]
No longer an issue with https://github.com/ansible/ansibullbot/pull/1316.
