### ISSUE TITLE
componentmatcher, moduleindexer, versionindexer and fileindexer should subclass gitrepo

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1086]
The GitRepo class offers an abstraction around a git checkout. ComponentMatcher, ModuleIndexer, VersionIndexer and FileIndexer all make use of GitRepo and add abstractions around it. Logically it seems that those classes should subclass GitRepo OR take an instance of GitRepo as an argument.

**Comment by mkrizek** [comment]
This has been partially addressed in https://github.com/ansible/ansibullbot/pull/1354
