### ISSUE TITLE
[non-urgent improvement] Avoid using unittest in tests

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansibullbot#1096]
While doing Python 3 compat PR I've also switched to pytest runner.
It's way better now, however current test suite often uses `unittest.TestCase` as a base for test classes.

So I'm here to ask everyone to stop doing this :)

There are a few reasons:
1) it prevents us from using `@pytest.mark.parametrize`
2) classes aren't actually needed in most cases and if we switch to fixtures we'll get better granular tests/deps.

**Comment by mkrizek** [comment]
While I agree there is no immediate action to take here outside of asking this in incoming pull requests. Instead of leaving this issue just sit here I am going to close this.

Thank you for raising this.

**Comment by webknjaz** [comment]
FTR I recently discovered that you may use pylint to make it enforce such lib replacements.
