### ISSUE TITLE
needs_triage only for core + network + certified

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#1098]
Do not apply needs_triage if:

1. -only- support:community
2. is WIP

**Comment by mkrizek** [comment]
> is WIP

Then add `needs_triage` when `WIP` is removed?

**Comment by gundalow** [comment]
I'd say only `1.`

We'd previously said that it would if a WIP PR was doing something we didn't want it would be better to look at it and educate/close at that point.

Plus bot logic to add/remove needs_triage based on WIP sounds like it would cause bugs

**Comment by mkrizek** [comment]
With non-core content not being in the repo anymore I think we can close this.
