### ISSUE TITLE
Automate restarting of CI with unstable results

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#1105]
When Shippable test results report unstable for the entire run (all jobs are success or unstable), then the bot should restart only the failed jobs. This should not be performed for runs which have reported failure or timeout instead, or have unstable results on individual jobs mixed with failure or timeout.

To prevent infinite restarts due to perpetually unstable tests, the bot should limit restarts to a reasonable number, perhaps no more than 3 - 5 times for a given commit. The Shippable API exposes information about the previous run if the current run has been restarted. These references can be followed back to each previous run in a chain of restarts to determine how many have been performed, regardless of whether it was done by a human or the bot.

Automating this will reduce the number of pull requests failing CI that need to be verified by a human.

**Comment by mattclay** [comment]
This will reduce the visibility of unstable tests. A future improvement, possibly to ansible-test and ansible-core-ci, will be to record unstable test results for easy reporting.

**Comment by gundalow** [comment]
As part of this can we poll CI status and remove `label/stale_ci` if there is a newer CI run? I believe at the moment that the bot will currently only read CI status if the PR changes (or it's a full Bot run).

There are occasions where I want to restart CI on failed runs, though without touching the PR (to avoid GitHub spam), such as in the run-up to a big PR review session.

**Comment by mkrizek** [comment]
@mattclay Does this apply to AZP?

**Comment by mattclay** [comment]
Closing, as this would not be helpful for AZP.
