### ISSUE TITLE
vmware_inventory fails to match contrib directory

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansibullbot#1108]
https://github.com/ansible/ansible/issues/48912 Here bot adds all VMware modules in component names. 

I tried to specify component command via comment - [here](https://github.com/ansible/ansible/issues/48912#issuecomment-441563916), no luck there as well.

**Comment by gundalow** [comment]
I think this was caused by the bot issue caused by use of yaml anchors and the fact that the bot wasn't copying internal data structures, which has been fixed.

Is this still an issue?

**Comment by Akasurde** [comment]
The issue never appeared again. I think we can close this for now. I will re-open this issue if I see this behaviour again. Thanks for the help.
