### ISSUE TITLE
bot no longer informing about test failures!

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansibullbot#1116]
The new module PR ansible/ansible#49605 has an initial commit which makes CI fail (lots of sanity tests, docs building tests), which used to cause ansibot to post a summary of the failed sanity tests. It hasn't done this for the last 7 hours.

**Comment by felixfontein** [comment]
Ok, now it just responded. Just a few hours late :) Anyone knows why?

**Comment by webknjaz** [comment]
Sometimes it gets stuck for different reasons (synchronizing data, catching up after restart) and then it takes time to reach certain checks.

**Comment by felixfontein** [comment]
Ok. Thanks for the reply!

I'll close this, as it doesn't seem to be a "real" problem.

**Comment by webknjaz** [comment]
I think it's more of a design/performance problem with hopefully gets away over time.
