### ISSUE TITLE
throttle need_rebase if manually removed

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#112]
https://github.com/ansible/ansible-modules-core/pull/2717

needs_rebase was added over and over again, but maybe the bot should avoid it if someone manually removed it.

**Comment by bcoca** [comment]
This leads to a lot of contributor frustration, specially on very 'PR popular' files, I would make this a manual thing for when someone is actually has had the time to review the PR (or after a shipit).

**Comment by jctanner** [comment]
needs_rebase detection is now accurately decided based on the detection of merge conflicts. If the label fluctuates on an issue, it's because i'm actively developing the bot's code OR the user is adding and removing merge conflicts between bot runs.
