### ISSUE TITLE
Please document proper component for reporting a bug of the ansible test setup

### ISSUE THREAD

**Issue by aknrdureegaesr** [ansible/ansibullbot#1120]
I have been reporting bugs regarding the automatic treatment of pull requests that attempt to contribute to the https://github.com/ansible/ansible/ repository. Which component to fill into the issue template in such a case is not (well) documented.

**Comment by gundalow** [comment]
@aknrdureegaesr Hi, appologies I appear to have missed this issue come in.

Where would you expect that information to be documented?

**Comment by aknrdureegaesr** [comment]
The template says 

```
##### COMPONENT NAME
<!--- Write the short name of the module, plugin, task or feature below, use your best guess if unsure -->
```

It would be nice if the template itself contained a link to some list of "modules, plugins, tasks, and features".

Another obvious place where one looking for such a link is the [Ansibullbot Help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md).

Where that information itself is documented, is secondary. Whatever fits.

**Comment by gundalow** [comment]
@aknrdureegaesr That's good feedback. What you suggested and some other discussions made me realise that https://docs.ansible.com/ansible/devel/community/reporting_bugs_and_features.html needs a lot of work.

I've created  https://github.com/ansible/ansible/issues/53520 which I hopes captures all of your points here, so I'll close this issue if that's OK?

Feel free to subscribe to https://github.com/ansible/ansible/issues/53520 would be great to get your review on this once we've got it updated.

**Comment by aknrdureegaesr** [comment]
This way of dealing with it is absolutely fine with me. Thanks, @gundalow !
