### ISSUE TITLE
changelog/fragment shouldn't block automerge

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1147]
https://github.com/ansible/ansible/pull/50655 contains:
* changelogs/fragments/50655-docker_swarm_service-update_order-idempotency.yml (new file)
* lib/ansible/modules/cloud/docker/docker_swarm_service.py (update to existing module)

`label/shipit` has been added though changelog blocks automerge.

This would be a good things to fix.

**Comment by dagwieers** [comment]
This is a showstopper for Working Group collaboration as it makes them dependable on outsiders to get stuff merged if they add a changelog fragment, e.g. https://github.com/ansible/ansible/pull/52574.
