### ISSUE TITLE
needs_revision label not getting removed, and blocking merge for unknown reason

### ISSUE THREAD

**Issue by AlanCoding** [ansible/ansibullbot#1151]
I would appreciate it if I could just get any help with the PR:

https://github.com/ansible/ansible/pull/37843

It has 3 shipits, and I don't know what else to do to unblock the bot for merge.

**Comment by jctanner** [comment]
2 reasons:

1. You had a comment with the phrase "needs_revision" in it, which I have corrected.
2. The PR violates the "1 module per PR" rule.
