### ISSUE TITLE
needs_rebase is added even though it shows false in status

### ISSUE THREAD

**Issue by bcoca** [ansible/ansibullbot#1154]
https://github.com/ansible/ansible/pull/50172

**Comment by wilmardo** [comment]
ansible/ansible#50417 < my PR seems to hit this bug as well. Rebased it today, the label hasn't been removed but the status shows `needs_rebase: False`

**Comment by gundalow** [comment]
In the case of https://github.com/ansible/ansible/pull/50172 I think the problem is that

```
This PR was evaluated as a potentially problematic PR for the following reasons:

More than 50 changed files.
Such PR can only be merged by human. Contact a Core team member to review this PR on IRC: #ansible-devel on irc.freenode.net
``` was triggered, that shouldn't cause any labels to be added

**Comment by mkrizek** [comment]
Closing per above.
