### ISSUE TITLE
MAINTAINERS parsing error (double space and unique)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#116]
On https://github.com/ansible/ansible-modules-core/pull/4303#issuecomment-237049018
I received an update of

`We notice that you are one of the maintainers (@privateip, @, @gundalow, @chouseknecht, @privateip, @gundalow) of this module, so when you think it's ready, please comment "shipit" and we will consider it for merging.`

1) Notice the empty `@` after privateip. This was caused by `MAINTAINERS-CORE.txt` having two spaces between `privateip  gundalow` which has now been fixed in https://github.com/ansible/ansibullbot/pull/117

2) Also it may be useful to sort/unique the list of maintainers. Maintainers may be listed multiple times when multiple files are changed in a single PR.

**Comment by jctanner** [comment]
Fixed by #117
