### ISSUE TITLE
GitHub Suggestion feature kind of breaks automerge

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansibullbot#1165]
When during review of a PR, the GitHub Suggestion feature is used both by the reviewer (suggesting something) and the author (adding the suggestion commit), the PR suddenly has more than one author, and automerge does not work anymore (if the number of different authors does not equal the number of commits for some random reason).

The bot still adds the `automerge` label, but the merge is not executed (`merge skipped for xxx`). Examples: ansible/ansible#50609, ansible/ansible#51216

**Comment by jctanner** [comment]
This is by design because we don't want to rebase+merge a large number of commits and we don't know if the authors want us to squash+merge and loose attribution for all but the original PR submitter.
