### ISSUE TITLE
False negative E305

### ISSUE THREAD

**Issue by resmo** [ansible/ansibullbot#1168]
module docs and doc fragement get merged correctly but the bot complains 

~~~
10:40 ERROR: Found 1 validate-modules issue(s) which need to be resolved:
10:40 ERROR: lib/ansible/modules/cloud/cloudscale/cloudscale_server.py:0:0: E305 DOCUMENTATION.options.api_timeout.description: required key not provided @ data['options']['api_timeout']['description']. Got None (75%)
~~~

https://github.com/ansible/ansible/pull/52069

**Comment by mattclay** [comment]
The [validate-modules](https://github.com/ansible/ansible/blob/devel/test/sanity/validate-modules/) sanity test is responsible for these messages, not the bot.

**Comment by resmo** [comment]
right.
