### ISSUE TITLE
bot identifies lot of files due to docs.ansible.com in description

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansibullbot#1173]
Bot identifies a lot of files due to occurrence of docs.ansible.com in issue description 
- https://github.com/ansible/ansible/issues/53274

**Comment by gundalow** [comment]
`docs.ansible.com` shouldn't match `docs` directory. It should only ping the docs team

**Comment by acozine** [comment]
I think this happened because that issue was marked `cloud` and referenced the AWS modules. @Akasurde if you see new issues that do this, please let me know, but I think this was an anomaly. 

@gundalow I think this issue can be closed.
