### ISSUE TITLE
Template provided labels breaks needs_triage

### ISSUE THREAD

**Issue by sivel** [ansible/ansibullbot#1174]
In 
https://github.com/ansible/ansible/pull/53356 we added labels that are auto applied by use of specific templates.

The action to add the label is done as the submitter which seems to prevent the bot from adding `needs_triage`

We need to solve that before adding template provided labels back.

**Comment by gundalow** [comment]
At the same time maybe worth checking to see if any other updates by the Issue reporter (adding a follow up comment, or editing comment0) don't trigger the removal of needs_triage
