### ISSUE TITLE
Changes to integration test blocked merge

### ISSUE THREAD

**Issue by kbreit** [ansible/ansibullbot#1182]
I worked with @felixfontein on this a little bit. The PR below should have been merged but is failing on the automerge. felix feels this is a bug.

Components
Metadata

waiting_on: maintainer
changes_requested_by: null
needs_info: False
needs_revision: False
needs_rebase: False
merge_commits: []
too many files or commits: False
mergeable_state: clean
shippable_status: success
maintainer_shipits (module maintainers): 1
community_shipits (namespace maintainers): 0
ansible_shipits (core team members): 1
shipit_actors (maintainers or core team members): acozine kbreit
shipit_actors_other: []
automerge: automerge !module file(s) test failed

https://github.com/ansible/ansible/pull/51415

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/pull/51415#issuecomment-475764423

**Comment by felixfontein** [comment]
Ah crap, that's the condition I forgot to check... I was so used that ansibot tags such PRs as `automerge` without merging them ;) Sorry!
