### ISSUE TITLE
Use inventory plugin metadata to set maintainers.

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansibullbot#1183]
~~Example ansible/ansible#54266: morph027 was not notified despite being [listed as the author](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/docker_swarm.py#L15). The field is shown [correctly in the documentation](https://docs.ansible.com/ansible/devel/plugins/inventory/docker_swarm.html#authors). Maybe it's related to author parsing, maybe something else. For now, we've "fixed" the situation by manually adding a BOTMETA entry (ansible/ansible#54305).~~

Sorry for reporting this wrongly, I've noticed this before (and blamed it on outdated metadata back then), and forgot to check well enough this time...

**Comment by jctanner** [comment]
https://api.github.com/repos/ansible/ansible/issues/54266 
`created_at: 2019-03-22T21:35:47Z`

https://api.github.com/repos/ansible/ansible/issues/comments/475793342 
`created_at: 2019-03-22T21:43:02Z` ...
```
I'm not sure whether this is a good idea, since it can easily be solved with a simple `when` conditional. I won't block it though ;) @morph027 any opinion on this?\r\n\r\nAnyway, I'm definitely against removing the leader from the `manager` group (the alternative listed in the PR description). That would be extremely confusing IMO.
```
https://api.github.com/repos/ansible/ansible/issues/54266/events 
`created_at: 2019-03-22T21:43:02Z, event: subscribed, actor.login: morp027`

https://api.github.com/repos/ansible/ansible/issues/comments/475795155
`created_at: 2019-03-22T21:50:06Z, user.login: ansibot`
```
cc @DBendit @akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet\n[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)\n<!--- boilerplate: notify --->
```

**Comment by jctanner** [comment]
@felixfontein chronologically, you made a comment that subscribed the author to the issue, before the bot had a chance to ping the author. The intent of the pings is to subscribe the person to the feed, and since it was arleady done by your comment, the bot did not need to duplicate the effort.

https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/plugins/notifications.py#L83-L94

**Comment by jctanner** [comment]
Something else to note, is that the bot doesn't currently parse metadata in inventory plugins. I wasn't aware that they had compliant metadata. We can extend the bot to read that data and apply the authorship to maintainership behavior is that is what the team wants.

**Comment by jctanner** [comment]
Reopening and setting this as a feature.

**Comment by gundalow** [comment]
@jctanner FYI we don't currently have CI that enforces the metadata in plugins, I know Sivel was working on a validator, though it's WIP/prototype. 
Also I expect a lot of modules to not be compliant, which I'm happy to fix if we get CI in.

**Comment by gundalow** [comment]
1) Should this information be in Plugins or BOTMETA
2) If plugins  then validate and fix up the existing plugin metadata
3) Update Bot if needed to deal with (1)&(2) as needed
4) Allocate people to do this

**Comment by mkrizek** [comment]
Superseded by https://github.com/ansible/ansibullbot/issues/1332
