### ISSUE TITLE
Bot removing `ci_verified` from old PRs

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#1188]
The bot is removing the `ci_verified` label from old PRs which have not seen any recent updates.

The most recent example is this PR: https://github.com/ansible/ansible/pull/38841

However, I've seen much older PRs updated as well: https://github.com/ansible/ansible/pull/24111

The last CI run from that PR was almost 2 years ago.

**Comment by mattclay** [comment]
https://app.shippable.com/runs/5903455c50821b07007ef4e5 is the latest CI run for ansible/ansible#24111 -- I was able to download all the artifacts and console logs for this run, and the data appears to be intact.

**Comment by jctanner** [comment]
Apparently I'm already handling this in the most logical way possible: https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/plugins/needs_revision.py#L578-L590

I'll have to figure out a better way to track whatever is going on in the prod instance.

**Comment by jctanner** [comment]
I checked both issues mentioned above locally and both fall into the same code path in my previous comment and ci_verified gets flipped back to True.

**Comment by mkrizek** [comment]
@mattclay @samdoran given that this issue is more than year old, is this still an issue?

**Comment by mattclay** [comment]
I haven't noticed this in a while, although it doesn't mean it isn't occurring. I'm fine closing this.

**Comment by mkrizek** [comment]
If you see this happening again please open a new issue or re-open this one, thanks!
