### ISSUE TITLE
changelog fragment causes automerge !module file(s) test failed

### ISSUE THREAD

**Issue by mkrizek** [ansible/ansibullbot#1205]
https://github.com/ansible/ansible/pull/57464

We might want to create an exception for changelog fragments?

**Comment by jctanner** [comment]
@mkrizek seems fine, but we might need to have some validation from ansible-test sanity or some sort of rules in ansibot to make sure people aren't spamming whatever they want in changelogs.

**Comment by mkrizek** [comment]
We have a changelog linter as part of `ansible-test sanity`: https://github.com/ansible/ansible/tree/devel/test/sanity/code-smell/changelog.py, https://github.com/ansible/ansible/tree/devel/packaging/release/changelogs/changelog.py. I think that should suffice.

cc @mattclay

**Comment by jctanner** [comment]
I guess what I meant was something to ensure no lewd remarks or curse words. Something to keep the text civil. Maybe an impossible task.

**Comment by mattclay** [comment]
Documentation content has higher visibility than changelog fragments, so I don't think we need to be more concerned about changelog content than we are over module docs.

**Comment by jctanner** [comment]
@mkrizek I guess we should go ahead and open the gates on this one?
