### ISSUE TITLE
shipit from people with commit rights to ansible/ansible seem to be ignored

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansibullbot#1222]
In ansible/ansible#58487, @resmo and me added `shipit`, next to another docker maintainer, but the bot didn't add shipit. bot_status showed that the bot only considered `shipit` from the other docker maintainer, but neither from me (I am maintainer + I have supershipit + commit rights) and resmo (commit rights).

**Comment by mkrizek** [comment]
Has this ever worked though? The bot seems to purposefully ignore 'review status' for the shipit workflow, from https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#when-will-your-pull-request-be-merged: `Approve pull request status is ignored...`.

You and resmo put `shipit` as a part of the 'approve' message whereas the maintainer used the `shipit` command in a comment so only his counts towards shipit.

cc'ing @jctanner for proper explanation :)

**Comment by felixfontein** [comment]
Yes, it did work, here are some examples: ansible/ansible#58039, ansible/ansible#57969, ansible/ansible#56975. You can find more when looking at recently closed PRs with label:docker and label:automerge. The bot does ignore that "Approve" was used, but it does consider (or at least, it used to in the past) the approval message. As long as that one contained a `shipit` or `LGTM`, it was fine.

**Comment by mkrizek** [comment]
Hrm, then something must have changed outside of the bot code because we don't get 'review events' in https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/plugins/shipit.py#L321 (why I thought it was never supported) and I don't see any change in the git recently that would affect this?

**Comment by mkrizek** [comment]
@felixfontein sorry for the confusion I created above :D It is fixed now, thanks for filing the issue!

**Comment by felixfontein** [comment]
@mkrizek thanks for fixing this :)
