### ISSUE TITLE
Track: automerge a new module

### ISSUE THREAD

**Issue by xuxiaowei0512** [ansible/ansibullbot#1237]
- [1] Some files changes to fix bugs, such as : lib/ansible/module_utils/network/cloudengine/ce.py, may they be auto-merged?

- [2] Can a new module be labeled 'automerge' ?
This is just a track, if it is necessary.
Thanks!

**Comment by xuxiaowei0512** [comment]
cc @jctanner 
Looking forward to your attention！

**Comment by jctanner** [comment]
Historically, new modules can not be automerged. There are exceptions for corporate partners such as Google and Microsoft where we give them commit or supershipit access to merge new plugins, but those are something we have business processes in place to mitigate risk.

**Comment by xuxiaowei0512** [comment]
Yeah,I know that you have less time to processes many modules.
I have discuss this with you on IRC a few days ago when I asked you for a hand.
It wiil be so cool that a new module or module_utils can be automerged.
Best regards.
