### ISSUE TITLE
Support ignore.txt deletions with supershipit

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#1239]
PRs can be auto-merged when they contain deletions to sanity ignore files. However, it appears this feature cannot be used with supershipit privileges.

See the existing support for sanity ignore files:

https://github.com/ansible/ansibullbot/blob/a6e389c92b786e803df7c4bd88c6715257c065eb/ansibullbot/triagers/plugins/shipit.py#L113-L119

Here's a PR which cannot be merged with supershipit privileges: https://github.com/ansible/ansible/pull/59324

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansibullbot/pull/1275
