### ISSUE TITLE
Fix broken unicode->bytes conversion in API responses

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansibullbot#1241]
I've found this @ https://sentry.io/organizations/red-hat-ansibullbot/issues/1122419350/?environment=prod&project=1336908
```python
...
_links: {
html: {"href":"u'https://github.com/ansible/ansible/pull/27757#pullrequestreview-54354326'"},
pull_request: {"href":"u'https://api.github.com/repos/ansible/ansible/pulls/27757'"}
},
...
```
The problem is: `"u'...'"`.

**Comment by Ilozuluchris** [comment]
Hi, @webknjaz I would like to have a crack at this, if possible. What do I need to know? Thanks

**Comment by webknjaz** [comment]
@Ilozuluchris it may be hard to find where this comes from if you don't have experience with hitting GitHub APIs and understanding of how the bot works for Ansible. While the error itself is a classical unicode/bytes conversion problem (i.e. somewhere in the code, there's some `str()` is called on a `bytes` var), this would also require an understanding of how bots work and diving deep into the codebase.

Please don't expect any guidance on this because everyone is busy working on the main project. This issue and the project itself is not really beginner-friendly.

If you're looking for some start contributing to open-source, I can suggest you look at https://opensource.guide/how-to-contribute/ for guidance.

**Comment by Ilozuluchris** [comment]
@webknjaz  I understand, thanks for the response.

**Comment by jctanner** [comment]
sentry.io can no longer load this issue, and without a traceback in the description I have nothing to go on.
