### ISSUE TITLE
bot removing ci_verified on failed PRs

### ISSUE THREAD

**Issue by jborean93** [ansible/ansibullbot#1259]
The bot is removing the `ci_verified` label that has been manually added.

Example PRs
* https://github.com/ansible/ansible/pull/60161
* https://github.com/ansible/ansible/pull/60131

**Comment by mkrizek** [comment]
@mattclay @samdoran @jborean93 just checking, is this still an issue?

**Comment by jborean93** [comment]
I can’t say I’ve seen it happening recently but I haven’t been paying close attention.

**Comment by mattclay** [comment]
I haven't noticed this in a while, although it doesn't mean it isn't occurring. I'm fine closing this.

**Comment by mkrizek** [comment]
If you see this happening again please open a new issue or re-open this one, thanks!
