### ISSUE TITLE
Bot links to wrong template, complains about version missing from feature request

### ISSUE THREAD

**Issue by felixfontein** [ansible/ansibullbot#1278]
In ansible/ansible#61967, ansibot suggested to use https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md as a template for a feature request, which doesn't contain anything useful. (It should have been https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/feature_request.md.)

Also, the bot complains about missing ansible version, while feature requests don't need that (the template doesn't contain that field).

**Comment by thomwiggers** [comment]
To be fair, the original version of that issue listed a wrong "issue type". See the edit history of the issue.

**Comment by felixfontein** [comment]
Ah, I missed the edit.

**Comment by tyler-e-marshall** [comment]
I just opened a feature request issue ([ansible/ansible/issues/65817](https://github.com/ansible/ansible/issues/65817)), and the same thing happened even though there is no edit history.

**Comment by gundalow** [comment]
Given that the Bot might not be sure I wonder if we should just link to each of the raw versions of https://github.com/ansible/ansible/tree/devel/.github/ISSUE_TEMPLATE
