### ISSUE TITLE
Bot to label new_module_directory modules

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1279]
## Background

As Ansible moves to collections we need to stop some new modules from being merged into gh/ansible/ansible.

To start we'd like to PRs which add new directories under `lib/ansible/modules/`

## Conditions
These PRs can be identified by either:
* If ` __init__.py` file is in the PR under `lib/ansible/modules/`
OR
* If a new directory is added in the PR under `lib/ansible/modules/`

## Outcomes

Add label https://github.com/ansible/ansible/labels/new_module_directory
No text (Bot comment) added at this time.

## Examples
https://github.com/ansible/ansible/pull/37378
https://github.com/ansible/ansible/pull/26529

**Comment by mkrizek** [comment]
@gundalow I am curious as to why existing `new_module` and `new_plugin` labels are not sufficient?

**Comment by gundalow** [comment]
This was to direct brand new groups of collections being added, so we could direct the contributor towards creating there own collection.

No longer needed (as migration has happened), so closing.
