### ISSUE TITLE
Consider not removing needs_triage automatically

### ISSUE THREAD

**Issue by sivel** [ansible/ansibullbot#1281]
I don't know what the rule is, or why `needs_triage` gets removed automatically when I comment on issues, but since we rely on this label in triage, we should make it an explicit action to remove it, instead of it being auto removed.

This would allow us to comment on issues without worry that they will then be missed in triage.

**Comment by jctanner** [comment]
relevant code https://github.com/ansible/ansibullbot/blob/51f5f92c1d2de9d9d0bbbb57e41623d248273c5c/ansibullbot/triagers/ansible.py#L2300-L2336

**Comment by jctanner** [comment]
My initial design for auto-removal was for community components with explicit maintainers. I didn't believe it was supposed to auto-remove on core stuff too, but we can revisit and debug that.

**Comment by gundalow** [comment]
Related https://github.com/ansible/ansibullbot/issues/1098

**Comment by gundalow** [comment]
AFAIK no community maintainers use `need_triage`.

Though check with Network Team

**Comment by sivel** [comment]
Example of issue where this can be seen: https://github.com/ansible/ansible/issues/66072

**Comment by gundalow** [comment]
Given that soon ansible/ansible will only contain support:core, the logic be

* Only if running against ansible/ansible add `needs_triage` when bot walks over issue & PRs
* Never remove needs_triage

Given that non-Core don't use needs_triage
