### ISSUE TITLE
documentation on stopping notifications.

### ISSUE THREAD

**Issue by nwsparks** [ansible/ansibullbot#1283]
Hello,

I am wondering how to stop receiving notifications. There should be documentation on this.

**Comment by mkrizek** [comment]
You can put your github name into `ignored` key BOTMETA: https://github.com/ansible/ansible/blob/b51a1bc429b934406a2c66efcd36cd2ca5b78d29/.github/BOTMETA.yml#L27 and then send a PR with the change.
