### ISSUE TITLE
rebuild_merge isn't merging

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1286]
https://github.com/ansible/ansible/pull/66847

**Comment by mkrizek** [comment]
It says ` automerge ci_state test failed`. I suspect the bot would eventually merge the PR given more time since re-opening the PR triggered CI again which had not finished yet at the time of `bot_status`.

**Comment by mkrizek** [comment]
Between `rebuild_merge` and re-opening PR is just 9 minutes, I think the bot was likely busy processing other issues and didn't get to the PR.
