### ISSUE TITLE
[3d] BOT: Collections support: Part 1

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1291]
Basic amount needed to do so Bot notifies the right people 

### Assumptions
* Bot only on community.general, AWS, VMware, Windows
* Python 2 only (Py3 support doesn't appear complete)
* Forked codebase is OK for the moment

### Requirements

- [x] Correctly identify authors based on DOCUMENTATION.author
- [x] Correctly identify authors based on BOTMETA
- [x] Read BOTMETA from Collections (gundalow)
- [x] BOTMETA to be read for community.general, aws, windows (requires https://github.com/ansible-community/collection_migration/issues/new)  (gundalow)
- [x] Command line option to specify which collection repo 
- [X] Remove support labels
- [x] labels for code type plugin, module_utils, action, etc
- [X] owner_pr label (helps fast track reviews)
  - https://github.com/ansible-collections/general/pull/14
  - Note: owner_pr only applies to modules and module_utils right now.  We probably want to enhance it to work with other plugins
- [x] Ensure on community.general subdirectories for modules are honored (w.r.t labels and maintainers)
- [ ] Don't write to `~/.ansibullbot/cache/ansible.
- [X] Define & use GH Teams from the correct GH Org
- [X] TEST `shipits` from Maintainers
- [ ] TEST merge
- [x] Multiple `templates/multiple_module_notify.j2` https://github.com/ansible-collections/community.general/pull/57
- [ ] Non-modules still showing as `support:core` - update botmeta, or logic in Bot?
- [ ] Pull in commits from ansibulbot:master that we want
- [X] `/rebuild` https://github.com/gundalow/ansibullbot/pull/15
- [X] community.general labels for categories and some subtopics
- [X] Replace hardcoded botnames. Use `ansibullbot/constants.py` add in a DEFAULT_BOTNAME
- [X] Image for GitHub Bot account
- [ ] Issue and PR template from `.github` repo
- [ ] MOTD with start/stop commands and log locations.
- [ ] Fix links in `templates` (new data structure for branch, ShippableID)
- [ ] Raise issue for Bot Part 2

### Running against other repos
* Update `BOTMETA` to define labels for plugin directories
* Create labels for above
* Give Bot user permissions on repo
* Add Shippable projectid

**Infra**

- [x] Dedicated host (Q: One instance per Collection, or just different webhook URLs)
- [ ] Basic monitoring
- [x] Dedicated GitHub account

### Depends on 
* Main bit of Bot work https://github.com/gundalow/ansibullbot/pull/7
* migrate to generate BOTMETA https://github.com/ansible-community/collection_migration/issues/429

### Part 2

* rebuild_merge
* label: backport, affects_X.Y

### Part 3

* Combine code back into main ansibullbot 
  * function to specify directories, rather than hardcoding module paths 
  * Remove Collection specific hacks
  * Guard items like support level around is_collection

**Comment by jctanner** [comment]
re: `Don't write to `~/.ansibullbot/cache/ansible` is that because it's the wrong location for cache files in your mind or because you simply don't want it to use a disk cache?

**Comment by gundalow** [comment]
> re: `Don't write to ~/.ansibullbot/cache/ansible` is that because it's the wrong location for cache files in your mind or because you simply don't want it to use a disk cache?

@jctanner @mkrizek We will need the bot running against 4+ collection repos. We thought running with different cache directories maybe needed, though maybe a Linux user (and therefore different homedir) per bot instance maybe best.

**Comment by mkrizek** [comment]
@gundalow Should this be moved to https://github.com/ansible-community/collection_bot now?

**Comment by mkrizek** [comment]
Closing per above.
