### ISSUE TITLE
Unsubscribe from messages

### ISSUE THREAD

**Issue by tomaszkiewicz** [ansible/ansibullbot#1307]
Hi, 

One day I submitted my MR to a module and after merging I became a contributor for that module. Now I get notified about every issue and MR for that module. I'd like to unsubscribe from that mails, but I cannot find a way how to do that. Can you help me?

**Comment by mkrizek** [comment]
This can be achieved by sending a pull request changing https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml. where you add `ignored: $your_github_username_listed_in_the_module_docs` to entries which correspond to files you have authored and no longer wish to be notified about. See the `BOTMETA.yml` file for examples.

**Comment by gundalow** [comment]
If the module ended up in community.general you'll also need to add an ignore entry into https://github.com/ansible-collections/community.general/blob/master/.github/BOTMETA.yml
