### ISSUE TITLE
Incorrect collection labels

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#1372]
In addition to [blacklisting update](https://github.com/ansible/ansibullbot/pull/1373) the following are missing the correct labels

https://github.com/ansible/ansible/issues/59558 should be netbox.netbox
https://github.com/ansible/ansible/issues/65817 should be community.aws
https://github.com/ansible/ansible/issues/67473 should be azure.azcollection
https://github.com/ansible/ansible/pull/67992 should be fortinet.fortios (applies to all of https://github.com/ansible/ansible/labels/collection%3Afrankshen01.testfortios)
https://github.com/ansible/ansible/pull/40320 should be community.general, not any of the others
https://github.com/ansible/ansible/pull/43682 should be community.general, not any of the others
https://github.com/ansible/ansible/pull/69789 should be ansible-base only?
https://github.com/ansible/ansible/pull/44983 should be ansible-base only?
https://github.com/ansible/ansible/pull/69789 should be ansible-base only?
https://github.com/ansible/ansible/pull/68627 should be ansible-base only?

**Comment by mkrizek** [comment]
> ansible/ansible#69789 should be ansible-base only?
ansible/ansible#44983 should be ansible-base only?
ansible/ansible#69789 should be ansible-base only?
ansible/ansible#68627 should be ansible-base only?

Those are not labeled `needs_collection_redirect` so those would not be auto-closed.

**Comment by mkrizek** [comment]
Looking at the rest.

**Comment by mkrizek** [comment]
So mostly the incorrect matching is due to components being the whole directory of modules like:
```
!component =lib/ansible/modules/net_tools/netbox/
!component =lib/ansible/modules/cloud/amazon/
!component =lib/ansible/modules/cloud/azure/
```

I was able to reduce some false positives in labels though. PR is coming.

**Comment by gundalow** [comment]
Thanks for the merge on other PR, and quick response here. 
I'd forgotten about `needs_collection_redirect`, I appreciate the clarification.

Is it safe for me to delete the labels with zero associates issues/PRs from https://github.com/ansible/ansible/labels?q=collection%3A ? That would make it easier to review the list.

Thinking out loud: If once #1374 has been merged, I wonder if it would be good to force run the bot over everything with a `collection:*` label?

**Comment by mkrizek** [comment]
> Thanks for the merge on other PR, and quick response here.
> I'd forgotten about `needs_collection_redirect`, I appreciate the clarification.
> 
> Is it safe for me to delete the labels with zero associates issues/PRs from https://github.com/ansible/ansible/labels?q=collection%3A ? That would make it easier to review the list.
> 

It should be fine (famous last words), go ahead and delete them, we'll see what happens :-)

> Thinking out loud: If once #1374 has been merged, I wonder if it would be good to force run the bot over everything with a `collection:*` label?

That might be wise, let me think on that.

**Comment by mkrizek** [comment]
@gundalow anything else to do here?

**Comment by mkrizek** [comment]
The problems mentioned in this issue were fixed. I am going to go ahead and close this. If there are additional issues, please open a new issue.
