### ISSUE TITLE
"Files identified in the description" links to file that no longer exists

### ISSUE THREAD

**Issue by n-st** [ansible/ansibullbot#1379]
In https://github.com/ansible/ansible/issues/70294, the bot reports:

> Files identified in the description:
> 
> * [`lib/ansible/modules/source_control/github/github_issue.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/github/github_issue.py)

<sub>(Nevermind that this was an incorrect guess.)</sub>

At the time the bot posted this, the file `github_issue.py` no longer existed in that location, so the link resulted in a 404.

The file did exists previously, e.g. in the `stable-2.9` branch, so perhaps the bot is operating on an outdated clone of the repository?
Or it is working on a different branch and shouldn't make assumptions (and links) for the devel branch?

**Comment by mkrizek** [comment]
We still need to identify components that were moved into collections in order to mark such issues with the `needs_collection_redirect` label and potentially auto-close them with a message informing where to file that particular issue.

**Comment by n-st** [comment]
Would it be possible to add a note to the bot's output in those cases, to avoid causing confusion about the broken link? Maybe even a link to a pre-collections branch where the file still existed?

**Comment by mkrizek** [comment]
That information is more or less already present via labels bot added to the issue, no?

**Comment by n-st** [comment]
I didn't see anything that would indicate that the dead link is not a bug, so I would say no.
