### ISSUE TITLE
When redirecting to collections, ansibullbot should link to the new repo or collection

### ISSUE THREAD

**Issue by acozine** [ansible/ansibullbot#1391]
As a developer or user, when Ansibullbot closes my PR or issue because it belongs in a collection, I would like an easy way to find the correct new repo.

Update https://github.com/ansible/ansibullbot/blob/master/templates/collection_migration.j2 to create a link to the repo if that is available, or to Galaxy.

Once this is done, we may need updates to https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md and/or to https://github.com/ansible/ansible/pull/70488/files.

**Comment by mkrizek** [comment]
It is not obvious from the template but this is already implemented:
https://github.com/ansible/ansibullbot/blob/507851159d23c1e222d95754e3e41b8f02139c47/ansibullbot/triagers/plugins/collection_facts.py#L78-L84

See an example:
```
(Epdb) pp self.render_boilerplate(self.meta,boilerplate=u'collection_migration')
('Thank you very much for your interest in Ansible. Ansible has migrated much '
 'of the content into separate repositories to allow for more rapid, \n'
 'independent development. We are closing this issue/PR because this content '
 'has been moved to one or more collection repositories.\n'
 '\n'
 '* lib/ansible/modules/windows/win_copy.ps1 -> '
 'https://galaxy.ansible.com/ansible/windows\n'
 '\n'
 'For further information, please see:\n'
 'https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md\n'
 '\n'
 '<!--- boilerplate: collection_migration --->')
```

Specifically this line:
```* lib/ansible/modules/windows/win_copy.ps1 -> https://galaxy.ansible.com/ansible/windows\n```

Is there anything else that should be done?

**Comment by mkrizek** [comment]
Closing per above.
