### ISSUE TITLE
Undocumented label needs_collection_redirect

### ISSUE THREAD

**Issue by mavit** [ansible/ansibullbot#1411]
The bot applies the label `needs_collection_redirect` to certain issues, but https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md does not explain what this label means.

**Comment by mkrizek** [comment]
Each label has a description if you do "mouse over" it (hover). Specifically, the `needs_collection_redirect` label points at https://github.com/ansible/ansibullbot/blob/master/docs/collection_migration.md.

**Comment by mkrizek** [comment]
Fixed in https://github.com/ansible/ansibullbot/pull/1412
