### ISSUE TITLE
Ansibullbot incorrectly marking PRs as having "stale_ci"

### ISSUE THREAD

**Issue by tremble** [ansible/ansibullbot#1420]
The CI run was still in progress and the Ansibullbot marked the PR as stale_ci

See for example:

https://github.com/ansible-collections/amazon.aws/pull/142#issuecomment-675868713

**Comment by jillr** [comment]
@tremble We're running a fork of (a fork of) the bot - could you report this in the aws collection repo please?
The collections branch will hopefully get merged in eventually, but the cloud bot has been deployed from a fork of https://github.com/gundalow/ansibullbot/tree/collections

**Comment by gundalow** [comment]
I've seen this when I forgot to update the Shippable Project ID.

It looks like `stale_ci` has been added to all PRs, though some have been removed by hand.

**Comment by gundalow** [comment]
Tracking as https://github.com/ansible-community/collection_bot/issues/4
