### ISSUE TITLE
Assign issues to module maintainers (as assignee)

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansibullbot#143]
Not sure if this was considered before, but I think it would be useful if ansibot would assign an issue to the module maintainer(s) by setting them as assignee in the Github web-interface.

In fact, if the maintainers become assignees, we may get rid of the additional comment in the issue-tracker since notifying the authors is no longer required.

The [ansibot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md) could be part of the information of the [ansibot](https://github.com/ansibot) user ? I.e. the URL and maybe he could fork/track the ansibullbot repository as well. Because the ansibot information is only useful for maintainers, getting rid of it in the issue flow does not confuse reporters either.

And the most important benefit for module maintainers and contributors is that you can more easily list all issues that are assigned to you. Currently I have to specifically search for a module in combination with waiting_for_maintainer, but I get a lot of false positives (modules I do not maintain, but somehow are mentioned, e.g. debug, fail, unarchive, etc...). If I am set to be assignee, I wouldn't have to look for every module to see if there's an issue I should be working on. (Granted, ansibot mailing you once a week helps, but with some unnecessary delay)

**Comment by jctanner** [comment]
Unfortunately, we can only assign users who are part of the ansible organization or are marked as collaborators.

```
(Epdb) issue.edit(assignee='jctanner')
(Epdb) issue.edit(assignee='dagwieers')
*** GithubException: 422 {u'documentation_url': u'https://developer.github.com/v3/issues/#edit-an-issue', u'message': u'Validation Failed', u'errors': [{u'field': u'assignee', u'code': u'invalid', u'resource': u'Issue', u'value': u'dagwieers'}]}
(Epdb)
```

The collaborator permissions are too broad to be of any use:
https://help.github.com/articles/permission-levels-for-a-user-account-repository/#collaborator-access-on-a-repository-owned-by-a-user-account

If github allowed finer grained permissions, I would definitely assign issues to the module owners. Unfortunately, we have to give away the keys to the kingdom to make someone assignable.

**Comment by jctanner** [comment]
https://github.com/ansible/ansibullbot/pull/228 will assign any maintainer(s) who can be assigned.

**Comment by dagwieers** [comment]
Great, and now wait for GitHub to get finer grained permissions !

**Comment by dagwieers** [comment]
Maybe a bonus-feature. In case the issue/PR can be assigned to a collaborator, don't make ansibot comment:

    /cc @name
    cllick here for bot help

Assuming that a collaborator is in the know of the process and is notified through the assignment already.
