### ISSUE TITLE
Bot fails to comment correctly

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansibullbot#1485]
https://github.com/ansible-collections/community.vmware/issues/573#issuecomment-761972152

**Comment by mkrizek** [comment]
Hi @Akasurde, I believe this should be reported against the collection bot at https://github.com/ansible-community/collection_bot.

**Comment by Akasurde** [comment]
@mkrizek thanks for the information. I reported it [here](https://github.com/ansible-community/collection_bot/issues/22)
