### ISSUE TITLE
Identify PRs in both core_review and community_review

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#15]
...and do the right thing.

**Comment by robynbergeron** [comment]
I assume this means "because it should only be in one bucket or the other, but not both."

Which normally is:
* If module is maintained by core, then core_review
* If module is maintained by awesome contributor(s), then community_review

Unless:
* Robyn / Greg / core team member / someone on a whitelist has added core_review for additional eyes / insight? (Then remove community_review, even if module is maintained by not core?) Or do we not want to use it for that purpose?

**Comment by gregdek** [comment]
Yes. core_ and community_ should be mutually exclusive states. If something is maintained by core, it belongs in core_review.  If something is maintained by community, it should be always be in community_review unless it has explicitly been escalated to core_review.

**Comment by robynbergeron** [comment]
Also, cases such as files/acl.py in core that are have a maintainer from both the core team (not the whole core team listed, just bcoca) and someone from the community?

**Comment by robynbergeron** [comment]
So I guess the process for escalation needs to be clearer then -- I realize we're going to be still be hands-on with a lot of this stuff for a while making sure that the bot is doing what it should be :) -- but I am guessing we should probably have some sort of special "HAIL SOMEONE PLZ" keyword to get eyes / assistance / auto-add a "special triage handling" label, or something,  to escalate things to a human. Shall I open a separate issue for such a thing?

**Comment by gregdek** [comment]
Until I hear otherwise, "bcoca" means "community bcoca" and we treat it no differently than any other community maintained module. If we want to create a policy that says "core members are not allowed to be community maintainers" we can do that, but the tool currently does not associate "bcoca" with "core". Only modules maintained by "ansible" are treated as core.

**Comment by robynbergeron** [comment]
Makes sense.  Maybe that should be a note in the maintainers file, or general documentation about how the bot works and what assumptions it makes. (FWIW: The non-coding parts of the bot stuff, like documentation, I can work on once it is more alive :D)

**Comment by gregdek** [comment]
This is now working as expected.
