### ISSUE TITLE
ansibullbot references a non-existing template

### ISSUE THREAD

**Issue by mariolenz** [ansible/ansibullbot#1582]
> Please set the description of this issue with this template:
> https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md

[source](https://github.com/ansible-collections/community.vmware/issues/880#issuecomment-856274815)

But https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE/bug_report.md doesn't exist.

**Comment by mkrizek** [comment]
There is no such link in this repository. This should be reported against https://github.com/ansible-community/collection_bot.

**Comment by mariolenz** [comment]
Sorry @mkrizek I didn't realize that there is another bot for the collections. I've opened ansible-community/collection_bot#29 to address the problem there.

**Comment by mkrizek** [comment]
@mariolenz No worries and thanks!
