### ISSUE TITLE
If a new module is added and the author says 'shipit' module is included

### ISSUE THREAD

**Issue by wimnat** [ansible/ansibullbot#160]
When someone writes a new module and the author says 'shipit', the bot marks the new module for inclusion because it thinks its from the author (which it is).  But really the bot should wait for more reviews if the module is brand new.

**Comment by resmo** [comment]
Could you show me an example?

There are a few so called *namespace* maintainer. When they create a new module in their namespace and comment with *shipit*, the bot will mark it for inclusion.

Here some examples
~~~yaml
cloud/centurylink/: clc-runner
cloud/cloudstack/: resmo dazworrall
cloud/vmware/: jctanner
~~~

**Comment by wimnat** [comment]
Ah that could be the case here. Netapp... https://github.com/ansible/ansible-modules-extras/pull/3028

**Comment by resmo** [comment]
confirmed https://github.com/ansible/ansibullbot/blob/master/MAINTAINERS-EXTRAS.txt#L178
