### ISSUE TITLE
"SIZE" parameter doesn't work with '+' in lvol module

### ISSUE THREAD

**Issue by Rakesh2904** [ansible/ansibullbot#1652]
Issue:
"SIZE" parameter doesn't work with '+' in lvol module

Error message:
Ex: "Bad size specification of '+200'"

Task details:
- 
      name: "Resizing the OS FS"
      lvol: 
        lv: "{{lv_name}}"
        size: "+{{input_size_mb}}M"
        vg: rootvg
        resizefs: true
      when: rootvg_free_space >= input_size_mb
      
 I am using lv and size as a input variable.
 
 Description
 We are trying to automate the OS FS extension in case of enough available space in VG, we are currently using Ansible Tower 3.8.6.and ANsible engine 2.9.27, I know that the 'size' parameter with '+/-' works with Ansible 3.0.0 so we are using requirements.yml to download the community.general collections and the download is a success but while launching the template we still have this issue which we are not supposed to get if community.general 5.3.0 is used.
 Please help us with a solution/fix
 
 PS: As a workaround we are using mathematical calculation (current_FS_size + Input_size) but that is a tedious and lengthy playbook which can be achieved if we can use the size parameter as intended.

**Comment by mkrizek** [comment]
This should have been reported against https://github.com/ansible-collections/community.general.
