### ISSUE TITLE
Detection of PR as a acceptable response to a bug

### ISSUE THREAD

**Issue by mscherer** [ansible/ansibullbot#168]
On https://github.com/ansible/ansible-modules-core/issues/3256 , maintainer did open a PR to fix a ticket. I think the bug shouldn't ping asking for feedback on the ticket, because that's a correct answer IMHO.

**Comment by jctanner** [comment]
@mscherer I agree. I'll try to sort this out asap.

**Comment by jctanner** [comment]
I think this is done?

**Comment by jctanner** [comment]
Need to review for triagev3.

**Comment by jctanner** [comment]
maintainers can use the resolved_by_pr command to achieve this effect.
