### ISSUE TITLE
maintainer for /test and label:test_pull_requests

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#183]
Hi,
Is it possible so that @gundalow and @mattclay get notified on any changes to `/test` (in any repo)

Also can they please get a `test_pull_requests` label added, the community have asked for this as it will help them find changes to review.

Thanks

**Comment by jctanner** [comment]
@gundalow pretty sure this was covered in https://github.com/ansible/ansibullbot/pull/197/files

**Comment by gundalow** [comment]
Yup and seems to be working well, thanks
