### ISSUE TITLE
module name extractor broken if "module" is part of the name

### ISSUE THREAD

**Issue by robinro** [ansible/ansibullbot#198]
There is a module called "apache2_module". While I agree the name is potentially confusing it is correct in the sense that this module deals with enabling/disabling apache2 modules.

The module name extractor fails to parse the module name, since the string 'module' is removed, see
https://github.com/ansible/ansibullbot/blob/47063c014c988f7de14000a8ad27e4cb6b4d75f3/lib/utils/extractors.py#L91

This leads to a lookup for `apache2_` and thus fails to find the maintainer.

**Comment by gundalow** [comment]
Good, spot. Thanks

**Comment by robinro** [comment]
Thanks for the quick fix!

**Comment by jctanner** [comment]
@robinro no problem, thanks for pointing out the busted line
