### ISSUE TITLE
Bot closes issue pointing to repository that does not exist

### ISSUE THREAD

**Issue by danielkza** [ansible/ansibullbot#216]
https://github.com/ansible/ansible-modules-core/issues/5409#issuecomment-261487211

**Comment by jctanner** [comment]
@danielkza yeah, that's a bug in the bot. It should have directed you to https://github.com/ansible/ansible/issues because all of the real code for include_role is there.

**Comment by jctanner** [comment]
REPOMERGE! no more redirects =)
