### ISSUE TITLE
Detect new/resolved PR merge conflicts

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#229]
When a PR has merge conflicts, the bot should detect this and:

- Add a label (needs_rebase) to indicate the issue has merge conflicts. This is useful for issue searches, as I'm not aware of a GitHub issue filter that allows searching on this.
- Add a comment explaining that there is a merge conflict and linking to or providing necessary instructions on how to resolve the conflict.

When a PR that previously had merge conflicts no longer has any, the bot should:

- Remove the label that was previously added (needs_rebase).

I believe this is functionality that the bot for core/extras previously provided, as seen here:

https://github.com/ansible/ansible-modules-core/pull/2172#issuecomment-162002107

**Comment by jctanner** [comment]
The detection and labeling has been implemented. Still brainstorming on non-spammy notifications.

**Comment by jctanner** [comment]
This was resolved already.
