### ISSUE TITLE
Handle old PRs lacking Shippable CI status

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#230]
The bot should detect old PRs which do not have Shippable CI status reported.

These PRs should be labeled with needs_rebase and a comment should be added instructing the user to rebase their PR. This will cause GitHub to re-trigger tests, something that cannot be done currently if the PR lacks a Shippable status.

PRs that would be covered by this:

- Old PRs with only Travis CI status which haven't seen new commits since we enabled Shippable.
- Old PRs with both Shippable and Travis. We can re-run Shippable, but can't clear Travis status.

This is a one-time use feature. Once existing PRs are labeled, it will not be needed again.

**Comment by jctanner** [comment]
@mattclay ...

> which haven't seen new commits since we enabled Shippable.

When was it enabled?

**Comment by mattclay** [comment]
@jctanner I disabled Travis on June 7th, 2016, so any CI jobs that ran on the 8th or later should only have Shippable status. If you're going to filter based on time instead of CI status, make sure you're looking at when the last CI job ran, instead of when the PR was created.

**Comment by jctanner** [comment]
Implemented byhttps://github.com/ansible/ansibullbot/pull/228/commits/611bf0a169692781af221dc31e478514b415cd29 and later commits.
