### ISSUE TITLE
Add set_approval

### ISSUE THREAD

**Issue by nerzhul** [ansible/ansibullbot#235]
Github has approval model.
It could be interesting for module maintainers to make the bot adding approval on a PR if it's valid or add a label ?

**Comment by jctanner** [comment]
@nerzhul are you talking about pull request reviews? https://help.github.com/articles/about-pull-request-reviews/

**Comment by nerzhul** [comment]
@jctanner yes, as maintainers only we cannot comment in official maintainers, but maybe permit the bot to approve merge requests with official API or make them as changes requested could be good

**Comment by jctanner** [comment]
so would the bot add it's self as a reviewer and then approve on behalf of the maintainer?

**Comment by jctanner** [comment]
non-admins for repos can make reviews and the bot does factor those into the shipt/automerge workflow.
