### ISSUE TITLE
Notify co-maintainers of shipit event when owner_pr

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#26]
In the cases of modules or files with multiple maintainers, when one of the co-maintainers submits a PR (and thus, gets labeled owner_pr and is merged automagically), when we apply the shipit label we should ping the other co-maintainers as a polite heads-up. 

(I don't know if this means we should handle the case where one of those maintainers then wants to move it out of shipit in the short time period between shipit label and actual merge, or if it can still be moved out of shipit via a needs_revision comment at that point or not, at least as the code stands today.)

**Comment by gregdek** [comment]
Makes sense.

**Comment by resmo** [comment]
this is implemented now as of #65

**Comment by resmo** [comment]
@gregdek this could be closed imho since #65 addresses it and has been merged.

**Comment by gregdek** [comment]
Yep. Thanks @resmo!
