### ISSUE TITLE
Periodically cross-check maintainer line in module against maintainers_core/extras files. 

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#27]
See https://github.com/ansible/ansible-modules-core/pull/2653 -

Note that: 
* Mark filed a PR to remove himself as maintainer and added ansible core team to some mysql modules
* Brian merged it
* maintainers_core, on the other hand, lists jmainguy as the maintainer

(This, ultimately, has hosed PRs such as https://github.com/ansible/ansible-modules-core/pull/2639 -- who should be pinging someone new, presumably jmainguy?)

Alternately: We remove the maintainer line out of all modules?

**Comment by gregdek** [comment]
We haven't officially noted that maintainer line in the module itself is deprecated. I'll add a new ticket for cwg and close this.

**Comment by gregdek** [comment]
Actually, to be clear (though still closed): we absolutely *want* the original authors to put their Github ID in, because it makes it easier for us -- but it's not essential, because git blame is more reliable.
