### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#277]
These modules are marked as "community" supported, but have no maintainers or have 'ansible' listed as the maintainer.

# 2017-03-03
lib/ansible/modules/cloud/amazon/cloudtrail.py,community,['ansible'],['ansible']
lib/ansible/modules/cloud/amazon/iam_cert.py,community,['ansible'],[]
lib/ansible/modules/cloud/amazon/iam_policy.py,community,['ansible'],['defionscode']
lib/ansible/modules/cloud/digital_ocean/digital_ocean_block_storage.py,community,[],[]
lib/ansible/modules/cloud/misc/serverless.py,community,[],[]
lib/ansible/modules/cloud/misc/virt.py,community,['ansible'],[]
lib/ansible/modules/cloud/packet/packet_device.py,community,[],[]
lib/ansible/modules/cloud/packet/packet_sshkey.py,community,[],[]
lib/ansible/modules/cloud/vmware/vmware_cluster.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_datacenter.py,community,['ansible'],['jcpowermac', 'kamsz']
lib/ansible/modules/cloud/vmware/vmware_dns_config.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_dvs_host.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_dvs_portgroup.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_dvswitch.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_host.py,community,['ansible'],['jcpowermac', 'mtnbikenc']
lib/ansible/modules/cloud/vmware/vmware_local_user_manager.py,community,['ansible'],[]
lib/ansible/modules/cloud/vmware/vmware_maintenancemode.py,community,['ansible'],[]
lib/ansible/modules/cloud/vmware/vmware_migrate_vmk.py,community,['ansible'],['jcpowermac', 'mtnbikenc']
lib/ansible/modules/cloud/vmware/vmware_portgroup.py,community,['ansible'],['jcpowermac', 'mtnbikenc']
lib/ansible/modules/cloud/vmware/vmware_target_canonical_facts.py,community,['ansible'],[]
lib/ansible/modules/cloud/vmware/vmware_vm_facts.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_vm_vss_dvs_migrate.py,community,['ansible'],['jcpowermac']
lib/ansible/modules/cloud/vmware/vmware_vmkernel.py,community,['ansible'],['jcpowermac', 'mtnbikenc']
lib/ansible/modules/cloud/vmware/vmware_vmkernel_ip_config.py,community,['ansible'],['jcpowermac', 'mtnbikenc']
lib/ansible/modules/cloud/vmware/vmware_vmotion.py,community,['ansible'],['bedecarroll']
lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py,community,['ansible'],['mtnbikenc']
lib/ansible/modules/cloud/vmware/vmware_vswitch.py,community,['ansible'],['jcpowermac', 'mtnbikenc']
lib/ansible/modules/cloud/vmware/vsphere_guest.py,community,['ansible'],['rhoop']
lib/ansible/modules/clustering/pacemaker_cluster.py,community,[],[]
lib/ansible/modules/crypto/openssl_privatekey.py,community,[],['Spredzy']
lib/ansible/modules/crypto/openssl_publickey.py,community,[],['Spredzy']
lib/ansible/modules/database/misc/mongodb_parameter.py,community,[],[]
lib/ansible/modules/database/misc/mongodb_user.py,community,[],['elliotttf']
lib/ansible/modules/database/mysql/mysql_db.py,community,[],['ansible']
lib/ansible/modules/database/postgresql/postgresql_db.py,community,['ansible'],['ansible']
lib/ansible/modules/database/postgresql/postgresql_schema.py,community,[],[]
lib/ansible/modules/database/postgresql/postgresql_user.py,community,['ansible'],['ansible']
lib/ansible/modules/files/tempfile.py,community,[],[]
lib/ansible/modules/network/citrix/netscaler.py,community,['ansible'],[]
lib/ansible/modules/network/cloudengine/ce_command.py,community,[],['CloudEngine-Ansible']
lib/ansible/modules/network/fortios/fortios_config.py,community,[],['bjolivot']
lib/ansible/modules/network/fortios/fortios_ipv4_policy.py,community,[],['bjolivot']
lib/ansible/modules/network/ipinfoio_facts.py,community,[],['akostyuk']
lib/ansible/modules/notification/osx_say.py,community,['ansible'],['ansible', 'mpdehaan']
lib/ansible/modules/packaging/language/gem.py,community,['ansible'],['ansible']
lib/ansible/modules/packaging/os/pulp_repo.py,community,[],['sysadmind']
lib/ansible/modules/packaging/os/sorcery.py,community,[],['vaygr']
lib/ansible/modules/packaging/os/swupd.py,community,[],['albertomurillo']
lib/ansible/modules/packaging/os/xbps.py,community,[],['dinoocch', 'the-maldridge']
lib/ansible/modules/remote_management/foreman/foreman.py,community,[],['ehelms']
lib/ansible/modules/remote_management/foreman/katello.py,community,[],['ehelms']
lib/ansible/modules/source_control/github_key.py,community,[],['erydo']
lib/ansible/modules/storage/zfs/zfs_facts.py,community,[],[u'xen0l']
lib/ansible/modules/storage/zfs/zpool_facts.py,community,[],[u'xen0l']
lib/ansible/modules/system/aix_inittab.py,community,[],['molekuul']
lib/ansible/modules/system/beadm.py,community,[],[u'xen0l']
lib/ansible/modules/system/facter.py,community,['ansible'],['ansible']
lib/ansible/modules/system/gconftool2.py,community,[],['kevensen']
lib/ansible/modules/system/ohai.py,community,['ansible'],['ansible', 'mpdehaan']
lib/ansible/modules/system/osx_defaults.py,community,['ansible'],['frenck']
lib/ansible/modules/system/pam_limits.py,community,['ansible'],['usawa']
lib/ansible/modules/system/pamd.py,community,[],['kevensen']
lib/ansible/modules/system/runit.py,community,[],['jsumners']
lib/ansible/modules/utilities/logic/set_stats.py,community,[],['bcoca']
lib/ansible/modules/web_infrastructure/htpasswd.py,community,['ansible'],['ansible']
lib/ansible/modules/web_infrastructure/jenkins_script.py,community,[],[]
lib/ansible/modules/web_infrastructure/nginx_status_facts.py,community,[],[u'resmo']
lib/ansible/modules/windows/win_iis_virtualdirectory.ps1,community,['ansible'],[]
lib/ansible/modules/windows/win_iis_virtualdirectory.py,community,['ansible'],[]
lib/ansible/modules/windows/win_msg.ps1,community,[],[]
lib/ansible/modules/windows/win_msg.py,community,[],['jhawkesworth']

**Comment by jctanner** [comment]
@jtyr we have you listed as the author for ldap_attr but you are not marked as the maintainer. Can I add you?

**Comment by jtyr** [comment]
@jctanner yes, please.

**Comment by ryansb** [comment]
Resolved `cloud/misc/serverless` with https://github.com/ansible/ansibullbot/pull/403

**Comment by bjolivot** [comment]
You can add me as maintainer for :
lib/ansible/modules/network/fortios/fortios_config.py,community,[],['bjolivot']
lib/ansible/modules/network/fortios/fortios_ipv4_policy.py,community,[],['bjolivot']

**Comment by jctanner** [comment]
With the migration to BOTMETA.yml, I think this is better tracked in the ansible/ansible repo.
