### ISSUE TITLE
PRs that sit for more than a week waiting for a maintainer response should verify that previously pinged maintainer is still the maintainer.

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#28]
No useful state change since last pass can sometimes be due to the person previously maintaining it is no longer the maintainer, but the new maintainer has not been pinged. (See https://github.com/ansible/ansible-modules-core/pull/2639.)

Alternative solutions:
-  Verify every time the bot runs through a PR that the current maintainer has been pinged / mentioned at least once by the bot in a comment, so that when maintainership transfers/additions happen, the new person can also be pinged. 
- When a line in the maintainers file changes, have a bot search all the PRs for old / previous maintainers, ping new / updated list of maintainers.

**Comment by gregdek** [comment]
This might still be an issue, so leaving it open.

**Comment by jctanner** [comment]
The bot ensures the current maintainer(s) have been pinged on every run, so this is no longer an issue.
