### ISSUE TITLE
duplicate_of / resolved_by_pr should work on PRs

### ISSUE THREAD

**Issue by willthames** [ansible/ansibullbot#322]
occasionally duplicate PRs happen - one gets merged, the other is left open.

See e.g. https://github.com/ansible/ansible/pull/20337

Should be a mechanism to mark the duplicate as to be closed (according to docs at least, `duplicate_of` and `resolved_by_pr` are only for issues)

**Comment by jctanner** [comment]
@willthames I'm pretty sure duplicate_of doesn't care if the issue is a pullrequest or not ...

https://github.com/ansible/ansibullbot/blob/master/lib/triagers/ansible.py#L955

In' 20337's case, I think either you weren't a maintainer yet OR the bot was down (rate limiting).
