### ISSUE TITLE
prbot dies when attempting to add boilerplate -- "AttributeError: 'list' object has no attribute 'replace'

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#36]
Found while running triage on core. Using the new and improved prbot.py freshly updated yesterday.

*****
3099 --- Fix: Incorrect parameters for module.set_fs_attributes_if_different in file.py
  Labels:  []
  Submitter:  bassco
  Maintainer(s): ansible
  Filename(s):  files/file.py
 
 
RECOMMENDED ACTIONS for  https://github.com/ansible/ansible-modules-core/pull/3099
   newlabel: core_review
   boilerplate: core_review_existing
 
Take recommended actions (y/N)?y
LABELS_URL:  https://api.github.com/repos/ansible/ansible-modules-core/issues/3099/labels{/name}
COMMENTS_URL:  https://api.github.com/repos/ansible/ansible-modules-core/issues/3099/comments
Traceback (most recent call last):
  File "./prbot.py", line 587, in <module>
    triage(shortpull['url'])
  File "./prbot.py", line 531, in triage
    mtext = pr_maintainers.replace(' ', ' @')
AttributeError: 'list' object has no attribute 'replace'

**Comment by gregdek** [comment]
old bot bug
