### ISSUE TITLE
Update README.md -- prbot has expanded options for usage, existing usage instructions no longer valid

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#37]
With #35 -- prbot now has additional options that should be specified at runtime.

(Yes, they actually print out when you run the thing, but still. :D)

usage: prbot.py [-h] [--ghuser GHUSER] [--ghpass GHPASS] [--ghtoken GHTOKEN]
                [--ghrepo {core,extras}] [--verbose] [--debug] [--pause]
                [--pr PR] [--startat STARTAT]

**Comment by resmo** [comment]
can be closed since #35 was reverted

**Comment by gregdek** [comment]
We have a new bot anyway :)
