### ISSUE TITLE
review old PR workflow and migrate to ISSUE_HELP

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#382]
https://github.com/ansible/community/blob/master/PR-FLOW.md

**Comment by gundalow** [comment]
So I think PR-FLOW.md should be deleted and anything relevant moved to https://github.com/ansible/ansible/blob/devel/MODULE_GUIDELINES.md or https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md


Note https://github.com/ansible/ansible/blob/devel/MODULE_GUIDELINES.md (and possibly other pages) link to PR-FLOW.md

**Comment by pilou-** [comment]
Related: https://github.com/ansible/community/issues/169
