### ISSUE TITLE
small_patch label

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#393]
Determine criteria for a "small" patch, and autolabel it.

**Comment by jctanner** [comment]
@abadger please detail your thoughts on what "small" means.

**Comment by abadger** [comment]
Starter heuristic might be: 
* no more than two hunks of code are changed.
* Each hunk should be at most three lines changed.

It's not a perfect heuristic for deciding if something is an easyfix but it does let us filter for things that might be easy to review.
