### ISSUE TITLE
comment with shippable failure messages

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#404]
mattclay [5:24 PM] 
I'd like to add to the bot support for commenting on CI failures on PRs. I'm part way to having machine readable data suitable for that purpose available via the Shippable API. Is that something that you'll have time to work on (the bot side of things) for the 2.4 release cycle, or should I plan on doing the bot integration?

mattclay [5:35 PM] 
My general goal is to have the bot able to grab results from those XML files and, if marked however we decide is needed, format the messages as comments on PRs. That way as I add support for more tests reporting that way, the bot can just pick them up and use them.

[5:36]  
You should be able to use the CI status links from the GH API to get the run_id.

**Comment by jctanner** [comment]
jctanner [5:33 PM] 
url = 'https://api.shippable.com/jobs/%s/jobTestReports' % job_id

[5:33]  
so that's the place?

mattclay [5:33 PM] 
Yeah, that's the one.

**Comment by jctanner** [comment]
mattclay [5:31 PM] 
I'm expecting the bot will format comments along the lines of:
```{message}:

{failure block}
```

[5:31]  
One of the things I need to do is add a some key/value pairs to instruct the bot when it's "safe" to use a test result and when it isn't.

[5:32]  
For example, failures on files that weren't changed in the PR is a good indication a failure occurred due to merging broken code instead of the PR being responsible.

**Comment by jctanner** [comment]
mattclay [5:26 PM] 
You can use the `test/utils/shippable/download.py` script to download the data I'm currently generating. It's just a simple script that uses the Shippable API, so the bot could do the same thing. You'll want to use the `--test-results` option: https://github.com/ansible/ansible/blob/devel/test/utils/shippable/download.py#L64

**Comment by mattclay** [comment]
Here's an example of what I'm thinking the bot will end up doing (https://github.com/ansible/ansible/pull/19492#issuecomment-284069294) with a test result (https://app.shippable.com/runs/58b9c098c2fe010500940cfb/1/tests).

**Comment by jctanner** [comment]
https://github.com/ansible/ansibullbot/pull/405
