### ISSUE TITLE
label recent PRs failing CI due to lack of shippable.yml with needs_rebase

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#406]
When a PR fails CI due to lack of a `shippable.yml`, the only fix is to rebase the branch. It would be useful for the bot to identify PRs with this problem and label them `needs_rebase`. If the PR is relatively recent (perhaps less than 1 week old) also add a rebase comment. Not adding the comment for older PRs will help prevent annoying contributors.

The only way I know of to identify these PRs is with the following criteria:

- CI status is failed
- There is only one job in the run on Shippable
- The console contains `__getYmlString could not fetch run yml file path/sha: .travis.yml/devel`

Here's an example: https://app.shippable.com/runs/58b8fc85c2fe01050093787b/1/console

**Comment by jctanner** [comment]
Confirmed with @gundalow that we can probably accomplish the same end result by checking the PR's branch for existence of the file. I think I can do that "cheaply" with the API.

**Comment by mattclay** [comment]
Although not directly tied to the Shippable job status, that should achieve the same result.

**Comment by jctanner** [comment]
@mattclay do you want an additional label for these besides needs_rebase?

**Comment by mattclay** [comment]
If it's easy to include, it could be useful. Perhaps something like `needs_shippable_yml`.
