### ISSUE TITLE
owner_pr is toggling

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#409]
https://github.com/ansible/ansible/pull/22201
@ansibot ansibot added the owner_pr label 2 minutes ago
@ansibot ansibot removed the owner_pr label just now

**Comment by gundalow** [comment]
Just a random guess, though I've seen some assignee toggling with Network issues. I wonder if that's because `@Qalthos` is in mixed case

**Comment by jctanner** [comment]
waffling detection should hopefully catch more of these.
