### ISSUE TITLE
Label CI failures with `ci_verified`

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#418]
Currently all failed PRs are manually reviewed and labeled with `ci_verified` as appropriate.

Now that there are bot-friendly `ansible-test-*.json` files created for test failures (currently being used for bot commenting), the bot has enough information to label PRs with `ci_verified` when all of the following criteria are met:

1. CI status for a Shippable run is `status=failed` (not timeout, canceled, etc.).
2. All jobs within the run must be `status=success` or meet all of the following criteria:
a. Are `status=failed` (not timeout, canceled, etc.).
b. Contains one or more `ansible-test-*.json` result files.
c. All of the `ansible-test-*.json` files contain the key `verified` with the value `true`.

If any of the criteria above are not met, no labeling needs to be performed by the bot. The PR will instead be picked up for manual review.

Currently this means that CI failures due only to failures of `TEST=other` are candidates for `ci_verified`. If there are failures in integration or unit tests, the above criteria cannot currently be met. However, this will change in the future as further enhancements are made to `ansible-test`.

NOTE: The `verified` key mentioned above has not yet been added to the test output. I will update this issue once there are PRs available to test against. When the `verified` key does exist, it will not always be `true`. This will happen when CI failures do not appear to be related to PR changes.

**Comment by mattclay** [comment]
Here's a PR which has the new results with `verified` keys in them:

https://github.com/ansible/ansible/pull/22384

You'll find a mix of both `true` and `false` values.

**Comment by mattclay** [comment]
Here's a PR which has the new results with `verified` only set to `false`:

https://github.com/ansible/ansible/pull/22680

**Comment by mattclay** [comment]
Here's a PR which has the new results with `verified` only set to `true`:

https://github.com/ansible/ansible/pull/22681

**Comment by mattclay** [comment]
An example with multiple failed jobs is lacking. I'll reference one here once I've created one.

**Comment by mattclay** [comment]
Here's a PR which should have one passing and one failing job:

https://github.com/ansible/ansible/pull/22720

This should be `!ci_verified`.

**Comment by jctanner** [comment]
@mattclay ...

> If any of the criteria above are not met, no labeling needs to be performed by the bot. The PR will instead be picked up for manual review.

Given this scenario:

1) submitter creates PR
2) shippable runs and fails
3) PR is classified as ci_verified and labeled accordingly by the bot
4) submitter creates a new commit 
5) shippable runs and fails
6) test failures are timeout or some other non-verified issue

The bot should or should not remove the ci_verified label?

**Comment by mattclay** [comment]
The bot should remove `ci_verified`, since the latest CI run is failed and not verified. The same would be true even if the label had been applied manually, instead of by the bot.

**Comment by jctanner** [comment]
@mattclay is this PR still ci_verified?

https://github.com/ansible/ansible/pull/18460
https://github.com/ansible/ansible/pull/18460/commits/beba49876974d05c38d98ec2ec855bf59eb480e2
https://app.shippable.com/runs/58926d0af2e87f0f00908ef0

It doesn't meet the criteria in this request, as far as I can tell.

**Comment by mattclay** [comment]
https://github.com/ansible/ansible/pull/18460 does not qualify for bot application of `ci_verified` because there are no test results available for the bot to process. However, it also does not qualify for bot removal of `ci_verified`, because the label was manually added after the last commit was made.

If another commit is made, or the PR were to pass CI, then the bot should remove the label, as the label is only valid for commits made prior to the label being applied. Of course if a subsequent CI run were to have test results which said it was verified, then the label could be kept (or reapplied).

**Comment by mattclay** [comment]
Shippable does not keep logs indefinitely. The bot should expect to be unable to get logs from old PRs. The length of time logs are kept is dependent on when CI ran because the retention period has been changed several times over the past few months.

These can be identified easily by spotting the "Logs are not available." message on the console. The output trying to get the test results using the API looks like this:

```
{"logType":"verbose","methodName":"jobTestReports|getSByJobId|callerId:573f3445d911710c00c93693|_untarReportsArchive","id":4005,"message":"untarReportsArchive jobId: 58926d0c8b639e1000269556 returned error: { [Error: Command failed: mkdir -p /tmp/58926d0c8b639e1000269556 && tar -xzvf /tmp/58926d0c8b639e1000269556.tar.gz --directory /tmp/58926d0c8b639e1000269556\n\ngzip: stdin: not in gzip format\ntar: Child returned status 1\ntar: Error is not recoverable: exiting now\n]\n  killed: false,\n  code: 2,\n  signal: null,\n  cmd: 'mkdir -p /tmp/58926d0c8b639e1000269556 && tar -xzvf /tmp/58926d0c8b639e1000269556.tar.gz --directory /tmp/58926d0c8b639e1000269556' }"}
```

**Comment by mattclay** [comment]
Just to be clear on my earlier comment about the bot not removing the label: The reason for this is because this feature request is only for adding the label. The already existing logic should be used for removing the label.
