### ISSUE TITLE
Bot leaves empty comment

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#421]
The bot sometimes leaves an empty comment on a PR:

https://github.com/ansible/ansible/pull/22636#issuecomment-286661413

I suspect this is due to the presence of an `ansible-test-*.json` file which has no messages.

**Comment by jctanner** [comment]
It had some content, but no test errors ..

```
<!-- job_id: 58c8e57431f2540600f23603 -->
<!-- job_id: 58c8e57431f2540600f23604 -->
<!-- job_id: /testresults/ansible-test-failure.json -->

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)
<!--- boilerplate: shippable_test_result --->
```

**Comment by mattclay** [comment]
Yes, the `ansible-test-failure.json` file will exist when there's an unhandled exception in the `TEST=other` tests. It's there so `verified=false` will be found by the bot, but it contains no failure messages.
