### ISSUE TITLE
Add a "close_me" state

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#44]
Sometimes a PR just isn't going to be accepted; maybe it's a duplicate, for instance. In that case, we should provide a mechanism for the maintainer of the module to request closure of the module.

**Comment by gregdek** [comment]
Should be a simple thing: 

1. Add close_me as an option to all the boilerplate;
2. Detection of close_me by a maintainer results in immediate closure with new boilerplate.

**Comment by jctanner** [comment]
Need to re-add for triagev3.
