### ISSUE TITLE
Support `shipit` command on all PRs.

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#461]
The bot should support the `shipit` command on all PRs.

This will be useful for requesting merge of a PR and letting the bot deal with re-running CI as needed.

Depends on #460

NOTE: Further discussion about the implementation of this feature is likely needed.

**Comment by mattclay** [comment]
This is actually a superset of the feature requested in #437

**Comment by jctanner** [comment]
Implemented in https://github.com/ansible/ansibullbot/pull/906
