### ISSUE TITLE
No auto assigning of Issues or PRs

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#500]
As discussed in Internal Core meeting 2017-04-25 we no longer want to auto assign issues based on `MAINTAINERS.txt`

**Comment by jctanner** [comment]
More context:

Github only allows us to assign people in the ansible org. Module maintainers generally aren't in our org and can't be assigned. The bot ends up only assigned people from the core team, which then makes it seem like we're actively working on something when we really aren't.
