### ISSUE TITLE
Maintainers for ec2_service 

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#506]
https://github.com/ansible/ansible/pull/20503#issuecomment-298143520

I don't see much activity on @java1guy profile. 

Do we have a way of seeing how active a maintainer is?

**Comment by simplesteph** [comment]
Cc @rmolok
If you guys aren't active can you please remove yourself so that the maintenance gets elevated to sub topic maintainers ?

**Comment by Java1Guy** [comment]
Short version of long story is that this was originally work for hire and yes, I'm on to other projects. I have submitted the PR to remove myself as maintainer.
Good luck, it's been fun! 👍

**Comment by rmorlok** [comment]
I'm sorry, I didn't realize I was still listed as a maintainer. I asked to be removed about 5 months ago.

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansibullbot/pull/526
