### ISSUE TITLE
Add "adopt_me" to modules without maintainers

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#51]
For modules that are maintained by core, we really need some kind of "adopt_me" boilerplate.

Then, if a non-bot user says "adopt_me", we label it somehow and kick it into a separate module adoption process (details tba).

**Comment by resmo** [comment]
how can the bot find out if a module is maintained by "core". If the maintainer is "ansible"? e.g. https://github.com/ansible/ansibullbot/blob/master/MAINTAINERS-CORE.txt#L3 ?

To handle it more common I would suggest to make it more generic and use a keyword e.g. "adopt_me" as maintainers, so the bot sees can act accordantly. This way we could also handle non- responsive maintainers or disappeared maintainers. Thoughts?

**Comment by gregdek** [comment]
Yes, currently having "ansible" as maintainer is equivalent to having "no community maintainer". My goal is to have every module in Extras (and most, maybe all in Core) to have a named maintainer that is not "ansible".

I like a generic "adopt_me" flag, yes. So how might it work? Hmm. 

Part of the problem is that "adopt_me" refers to the module itself, not the PR; it's just that the PR is the only available mechanism we have to communicate that a module is in "adopt_me" state.

We also have the issue of "when someone puts one PR into adopt_me, all other PRs for that module should also go into adopt_me". 

The solution is not clear to me yet. May be worth a discussion at an upcoming meeting.

**Comment by resmo** [comment]
I would suggest to replace all "ansible" with "adopt_me" for those modules which can be adopted, e.g. all in extras and a few less in core. This would be super easy to handle by the bot.

**Comment by userlerueda** [comment]
What is the manual way of adopting a module ?

**Comment by gregdek** [comment]
@userlerueda The right way for now is to submit a PR to the ansibullbot maintainers file, though it's not currently documented. I'll file a separate issue to address that, and we'll close this issue, since it's no longer quite right (see #428 for details). Thanks!
