### ISSUE TITLE
Stop and/or notify if no maintainer is found

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#55]
New bot seems to ignore the case when an existing module does not yet have a maintainer listed. 

Previous bot treated this as FATAL, and I would immediately stop the run and edit the appropriate maintainers file.  

New behavior should probably be to skip and and send some kind of notification to the bot team.

**Comment by gregdek** [comment]
To be clear: In the long term, when this is fully automated, this should probably send a notification. In the short term, though, I think I'd like it to fail as fatal.

**Comment by resmo** [comment]
the bot uses `ansible/core` (see https://github.com/ansible/ansibullbot/blob/master/triage.py#L475) as maintainer in this case. I tried to avoid sys.exit but would be easy to do. I'll make a PR.

**Comment by gregdek** [comment]
Wait! I've changed my mind. :)

Now that I've taken the plunge to run this in automated mode, I think the right answer is actually to just note that there's no listed maintainer in the PR itself. So maybe just new boilerplate:

"maintainer unknown ping @gregdek @resmo @robynbergeron" 

Or something like. And then just leave it completely untriaged otherwise. The Github mention should be enough to get us to fix it in short order.

**Comment by resmo** [comment]
ok then :)
