### ISSUE TITLE
incorrect component labels on module PR

### ISSUE THREAD

**Issue by s-hertel** [ansible/ansibullbot#558]
Bot running amok with incorrect labels. See https://github.com/ansible/ansible/pull/25166.

**Comment by mkrizek** [comment]
I can't reproduce this and can't see what the original issue looked like since the original issue has been altered before GitHub had introduced the feature to see issue's history. We'll see if that happens again.

**Comment by s-hertel** [comment]
I don't think I've really seen this happen since.
