### ISSUE TITLE
Changing PR states for unclear reasons

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#56]
Some instances of a PR being put into a *_review state when it's already in a needs_* state:

* (e1793, e1722, c2438, c2278, c1665) Trying to take a PR in "needs_info" state and putting it back into community_review/core_review. Bot should leave it in "needs_info" until we get an explicit ready_for_review.

* (e1663, c3015) Trying to take a PR in "needs_revision" state and putting it back into community_review. Not sure why.

* (e1480) Trying to take a PR in "needs_rebase" state and putting it back into community_review. Not sure why.

**Comment by resmo** [comment]
investigating...
