### ISSUE TITLE
use native metadata parser instead of custom implementation

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#609]
Replace https://github.com/ansible/ansibullbot/blob/master/lib/utils/moduletools.py#L743 with https://github.com/ansible/ansible/blob/devel/hacking/metadata-tool.py#L200

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/pull/26198

**Comment by mkrizek** [comment]
Superseded by https://github.com/ansible/ansibullbot/issues/1332
