### ISSUE TITLE
sanity test failure makes search-by-module-name too noisy

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansibullbot#626]
eg: https://github.com/ansible/ansible/pull/26015#issuecomment-310411733 - the bot comment with the test failure (while awesome) in this case contains every module name in the command, so when searching for issues/PRs by module name, these bogus results come up... Need to figure out a way to mask the module names, possibly in the ansible-test command itself?

cc @mattclay

**Comment by jctanner** [comment]
If this is going to happen, I would prefer it be done in the shippable data rather than having ansibot need to further understand the data.

**Comment by mattclay** [comment]
I agree this should be done by ansible-test and not by the bot. I've created https://github.com/ansible/ansible/issues/26467 to track this as a feature request which I've assigned to myself.
