### ISSUE TITLE
Ignore `test/sanity/pep8/legacy-files.txt` for `test_pull_requests` label

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#629]
If `test/sanity/pep8/legacy-files.txt` is the only `test/` file modified by a PR, the bot should not apply the `test_pull_requests` label. This will avoid adding the `test_pull_requests` label when a PR only cleans up legacy PEP 8 issues without making any other test related changes.

This request came out of discussion from the TWG.

See: https://github.com/ansible/community/issues/114#issuecomment-313017022

**Comment by pilou-** [comment]
I would be nice if the bot didn't consider that any deletions of `test/sanity/*/*.txt` files were [changes to other files in the PR](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#existing-modules). It seems that this classification prevent automerge.

**Comment by mattclay** [comment]
This has been implemented.
