### ISSUE TITLE
Bot counts modules as core-maintained when they are not

### ISSUE THREAD

**Issue by ryansb** [ansible/ansibullbot#634]
Example issue: https://github.com/ansible/ansible/pull/24406

The bot counts modules that are supported by community or curated as supported by core, shown in the bot_status messages. This happens on renames (known issue) and on non-rename PRs.

**Comment by jctanner** [comment]
I think the bad classification for !renamed was fixed in https://github.com/ansible/ansibullbot/commit/f9e1325521d2ec2a47ed7cf844ff2c2177d40bb4
