### ISSUE TITLE
hasty "shipits" for owner_prs for new modules

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#64]
2:35 PM <caphrim007> gregdek: ansibull-bot marked 'shipit' on a PR that was only meant to be a comment
2:35 PM <caphrim007> https://github.com/ansible/ansible-modules-extras/pull/1370#issuecomment-203524951
2:35 PM <daemoniz> it was just that good
2:35 PM → cloudtrainme joined  ⇐ kushal quit  
2:36 PM <caphrim007> hehe. ansibull-bot is 2 days early. april 1st isn't until friday
2:36 PM → josuebrunel joined  ⇐ ageorgop quit  
2:36 PM <•gregdek> Ah, thanks. Looks like the bot is too aggressively giving "shipits" for new modules. resmo: ^^^
2:36 PM → ppinkert_ joined (~pinky@c-98-229-27-71.hsd1.ma.comcast.net)
2:37 PM <•gregdek> Gave "owner_pr shipit" to a module that isn't a module yet. :)

**Comment by resmo** [comment]
imho this can be closed

**Comment by gregdek** [comment]
Agreed.
