### ISSUE TITLE
Proposal: use tenacity library

### ISSUE THREAD

**Issue by pilou-** [ansible/ansibullbot#668]
Retry pattern is used in different files:
- [ansibullbot/utils/shippable_api.py#L63](https://github.com/ansible/ansibullbot/blob/0ebc2538c539fce920c1debccbc9b1d8d21881f8/ansibullbot/utils/shippable_api.py#L63)
- [ansibullbot/utils/shippable_api.py#L362](https://github.com/ansible/ansibullbot/blob/0ebc2538c539fce920c1debccbc9b1d8d21881f8/ansibullbot/utils/shippable_api.py#L362)
- [ansibullbot/decorators/github.py#L27](https://github.com/ansible/ansibullbot/blob/0ebc2538c539fce920c1debccbc9b1d8d21881f8/ansibullbot/decorators/github.py#L27)
- [ansibullbot/decorators/github.py#L40](https://github.com/ansible/ansibullbot/blob/0ebc2538c539fce920c1debccbc9b1d8d21881f8/ansibullbot/decorators/github.py#L40)
- [ansibullbot/decorators/github.py#L84](https://github.com/ansible/ansibullbot/blob/0ebc2538c539fce920c1debccbc9b1d8d21881f8/ansibullbot/decorators/github.py#L84)

What do you think of using the [tenacity](http://tenacity.readthedocs.io/en/latest/) _general-purpose retrying Python library_ (Github [repository](https://github.com/jd/tenacity), PyPI [package](https://pypi.python.org/pypi/tenacity)) there ?

**Comment by jctanner** [comment]
@pilou- looks good to me. I'm actually in favor of ripping out all custom code in favor of third party libs wherever possible.

**Comment by jctanner** [comment]
We'll use this where it makes sense. The RateLimited decorator handles more edge cases specific to pygithub.
