### ISSUE TITLE
Should review comment be checked when looking for approval ?

### ISSUE THREAD

**Issue by pilou-** [ansible/ansibullbot#677]
For example [here](https://github.com/ansible/ansible/pull/26839) reviewer added `shipit` in `APPROVED` review comment (but not in a issue comment). Should we support this ?

This is an easy update.

**Comment by jctanner** [comment]
It's hard to say. Some people think a review approval is for a change requested or for a section of the code. Sometimes people think a review approval is for the entirety of the patch.

I don't know how we can differentiate the 2 possible intents, which is why I haven't worked on this yet.

**Comment by pilou-** [comment]
The Github documentation [mentions](https://help.github.com/articles/about-pull-request-reviews/#) that `Approve` means:
> Submit feedback and _approve merging_ the changes proposed in the pull request

**Comment by jctanner** [comment]
resolved by https://github.com/ansible/ansibullbot/pull/727
