### ISSUE TITLE
When changing maintainer to core_review, need to ensure somehow that we prompt them for "shipit" or "needs_revision"

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#71]
https://github.com/ansible/ansible-modules-extras/pull/1354 is an example.

The maintainer was changed to the core team, who requested revisions in a diff, but did not state the regular boilerplate that is normally given to maintainers ("please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.") In this case the core team manually changed the label to needs_revision, but didn't state needs_revision, and thus the maintainer was not pinged for some time until the bot noticed that it was in a needs_revision state for X number of days, and then it prompted him.

Perhaps this should be an "anytime the reviewer is changed from community_review label to core_review label, add core_review boilerplate text" (which should be fixed also, because it says nothing about shipit vs. needs_revision, but that's yet another ticket.)

**Comment by gregdek** [comment]
Moving a PR from community review to core review is not currently something the bot handles anyway. It's a manual process for now.
