### ISSUE TITLE
When the core_review label is applied, apply appropriate text including "shipit" or "needs_revision" wording.

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#72]
https://github.com/ansible/ansible-modules-extras/pull/1707 is an example.

Text currently says:

"Thanks @submitterofstuffandthings for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

[This message brought to you by your friendly Ansibull-bot.]"

It should probably say,

"Thanks @submitterofstuffandthings for this PR. This module is maintained by the Ansible core team, so it can take a while for patches to be reviewed. Thanks for your patience.

Core team: please review according to guidelines (http://docs.ansible.com/ansible/developing_modules.html#module-checklist) and comment with text 'shipit' or 'needs_revision' as appropriate.

[This message brought to you by your friendly Ansibull-bot.]"

And this is for a few reasons:
* Keep consistency for community_review and core_review items; we don't want to confuse issue submitters with what may appear to be different types of workflow.
* Core folks should be using the proper bot word tags to ensure that the bot workflow behaves correctly and providing text to also appropriately prompt submitters / issue creators to do the right thing. Additionally, even if the core team "knows" that they should do this, it still lacks consistency (as mentioned above) and the addition of more core team members may mean that a new member may not know to do this. 

Also:
* Should also ask core team to not manually change labels if possible to avoid breaking bot workflow.  
* Not sure how this applies in the shipit case.

**Comment by gregdek** [comment]
I agree, except "shipit" doesn't make sense; if they like the change, they can and should merge it directly.
