### ISSUE TITLE
Detect when a core team member changes label

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#73]
...and deal with the boilerplate according.

**Comment by resmo** [comment]
hmm this could be a tricky one. 

IMHO it would be much easier to implement if the core team member does a comment without changing the label. The labels are used for the current state, if the core team member changes the label the bot uses it as current state, it has no clue what it look the last time it checked.

**Comment by jctanner** [comment]
This is handled by the historywrapper now. In get_commands, the action of adding or removing a label is treated as an implicit command.

https://github.com/ansible/ansibullbot/blob/efeda6f607cac16c042f645a2252db7bb27bd77a/lib/wrappers/historywrapper.py#L184
