### ISSUE TITLE
Simpler timeout handling

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#74]
Right now our timeout handling is quite primitive. Basically, we rely on comments from a "bot" user, when we should probably add separate timeout labels and use them. 

Simplified workflow for all non-new-module PRs could be:
- In community_review and no response from anyone for two weeks? Warn maintainer and put into pending action.
- In needs_\* and no comment from anyone for two weeks? Warn maintainer and put into pending action.

We can then have a weekly review of all PRs in pending_action, taking action as needed.

In total, we should give a month for actions or discussion: two weeks until pending_action is applied, and then another two weeks until some action is taken manually.

**Comment by resmo** [comment]
I also wanted to suggest some improvements for the timeout handling as it is too error-prone for the bot currently. The enhancement you worked out looks good to me. Working on it.

**Comment by jctanner** [comment]
needs_info has it's own timeout mechanisms, so this is "done"
