### ISSUE TITLE
Pull request updating module supported by community should not wait on `ansible`.

### ISSUE THREAD

**Issue by pilou-** [ansible/ansibullbot#779]
Example: https://github.com/ansible/ansible/pull/23447#issuecomment-331966447
```
waiting_on: ansible
module: timezone
supported_by: community
```
In this context `ansible` means `core team`.

Thanks to misc for pointing that.

**Comment by pilou-** [comment]
Since cdf978a80a5aa238d15915e54d7f1d483254cf47, `get_component_match_facts` from checks if `support` field is set in `BOTMETA.yml`. If not, `core` is used [by default](https://github.com/ansible/ansibullbot/blob/ba1d1b66d18c822d7e8af71d14447054287180c5/ansibullbot/utils/file_tools.py#L21). When a module (for example `lib/ansible/modules/system/timezone.py`) is listed in `BOTMETA.yml` without a `support` field, then `waiting_on` value is `ansible`.

`get_review_facts` (from `shipit` plugin) checks `['module_match']['metadata']['supported_by']` value defined in source code, in this case `supported_by` value comes from module source code.

I propose to:
- remove `is_core` metadata
- document in BOTMETA.yml headers that `support` field don't override `supported_by value` defined in module source code
- for modules: use `['module_match']['metadata']['supported_by']` instead of `component_matches` (`support` field in metadata would be ignored for modules) when computing value of `waiting_on`.

**Comment by gundalow** [comment]
@pilou- Is this still an issue?

**Comment by mkrizek** [comment]
With the community content being in collections now we can close this.
