### ISSUE TITLE
Remove "needs_rebase" as a separate state

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#78]
Because what we really mean is "just another flavor of needs_revision."

From IRC today:

 <•gregdek> ...we could always just do away with needs_rebase as its own state. And change the boilerplate to say "this needs revision because one of these things: (a) a reviewer said so; (b) it fails travis; (c) it fails to merge in its current state. Please Do The Right Thing Now." :)
4:15 PM <resmo> gregdek: too simple :)
4:15 PM <•gregdek> Then the problem is kinda solved, the submitter gets important information, and we don't automatically put things back into *_review until the submitter says "ready_for_review".

**Comment by jctanner** [comment]
Completed in post-repomerge bot.
