### ISSUE TITLE
first time contributor label

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#785]
If the user is a first time PR submitter, label the PR accordingly

**Comment by jctanner** [comment]
Need to do some research on the most efficient methods to determine if the username has previously committed or sent a PR.

**Comment by jctanner** [comment]
@pilou- any thoughts on this?

**Comment by gregdek** [comment]
Following this :)

**Comment by pilou-** [comment]
Note there is a `contributor`/`first-time contributor` badge (https://github.com/ansible/ansible/pull/30738#issue-259759330). However it doesn't seem possible to filter (using website or API) pull requests with `contributor` or `first-time contributor` badge.

There are some ways to proceed:
1. with GraphQL
    ```
    query {
      user(login: "mscherer") {
        login
        contributedRepositories(first: 100, privacy: PUBLIC) {
          totalCount
          edges {
            node {
                nameWithOwner
            }
            cursor
          }
        }
      }
    }
    ```
1. scrapping the pull request web page, looking for the contributor badge
1. using v3 API: 
https://github.com/ansible/ansible/commits/devel?author=mscherer (cons: it only checks one branch)

**Comment by pilou-** [comment]
@jctanner you found a way to fetch badge information using GraphQL, great :)
