### ISSUE TITLE
Prevent notification storms on corrupted/improper PRs

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansibullbot#787]
So almost daily we get some broken PRs with lots of existing commits in a new PR. Often the owner of the branch did something wrong and has no clue to resolve it and eventually just closes the ticket. But the real damage is already done at the time, as everybody involved with any of these commits (directly or indirectly) are getting mailed by ansibot.

Examples:
- ansible/ansible#31505
- ansible/ansible#31654
- ansible/ansible#31665

Either we should be able to identify these corrupt PRs, or at least prevent to send out notifications to more than an arbitrary number of people e.g. 25 ? Maybe check existing cases for a good treshold ?

**Comment by pilou-** [comment]
Does `more than 30 commits and more than 30 files modified` a good filter for these PR ?

**Comment by cben** [comment]
Proposal: a simple "more than N people at once" limit for automatic notification.

If more than that, ansibot instead of mentioning all the people would explain that it suspects it's a mistake, and will list the usernames it would have cc'd  (without `@`, or within backticks literal), so humans can (A) understand what's happening (B) manually cc all or some people if really intended (eg. large cross-cutting refactoring).

**Comment by jctanner** [comment]
first implementation could be to disable all notifications if a merge commit is detected (something we already check for).

**Comment by dagwieers** [comment]
Another common case recently we also have to consider:
https://github.com/ansible/ansible/issues/33448#issuecomment-348435111

**Comment by dagwieers** [comment]
We are now closing one specific case, but I'd like to also consider a more general solution for other causes (like the one in my previous comment). I want to prevent any more of these cases because they make people want to drop out of any notifications.

**Comment by gundalow** [comment]
Seems to be back. opened https://github.com/ansible/ansibullbot/issues/837

**Comment by dagwieers** [comment]
https://github.com/ansible/ansible/pull/34011
