### ISSUE TITLE
issuebot: when we handle issues, check to make sure correct repository

### ISSUE THREAD

**Issue by robynbergeron** [ansible/ansibullbot#8]
I've already seen three issues today that were filed in core instead of extras.

**Comment by gregdek** [comment]
Closing because this is PRbot, not issuebot. :)

**Comment by robynbergeron** [comment]
I thought that ansibullbot would be the repository where both prbot and issuebot lived :p

**Comment by gregdek** [comment]
Oh, you're right.

**Comment by robynbergeron** [comment]
This is now documented as part of the requsted workflow for the issuebot. Closing, unless someone feels like it should stay open. 

https://github.com/robynbergeron/thingsandstuff/blob/master/issue_workflow_v1

**Comment by jctanner** [comment]
This is already done in the issue triage code.
