### ISSUE TITLE
detect and label pep8

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#810]
https://github.com/ansible/ansible/pull/32623/files

* changes to test/sanity/pep8/legacy-files.txt
* pep8 in the commit message / title / description / etc

**Comment by dagwieers** [comment]
I hope at some point we can get rid of the legacy-files.txt file and get this over with altogether.
I have been working towards this, but we still have nearly 300 files to go...

**Comment by dagwieers** [comment]
I added support for the legacy-files.txt in BOTMETA.yml and tagged existing PRs in the same effort.

**Comment by gundalow** [comment]
No longer needed as we've bulk fixed everything
