### ISSUE TITLE
Metadata labelling and unit/integration test policy (shipit)

### ISSUE THREAD

**Issue by willthames** [ansible/ansibullbot#811]
I would like module PRs to be labelled with stableinterface, core, preview etc based on metadata

For AWS, this allows us to check that non-preview modules have associated tests.

Ideally we'd add needs_tests labels to AWS non-preview modules that are feature requests and do not have existing integration tests, but that might be a special case too far for ansibot!

**Comment by gundalow** [comment]
I like this.

So based on what we do for support: https://github.com/ansible/ansible/labels?q=support

I wonder if we'd want something like:
```
status:stableinterface
status:core
status:preview
```

We already have `label/deprecated` so I don't think we need a `status:deprecated`

Need to remember that a module may have more that one `status`, the full list is defined at https://docs.ansible.com/ansible/devel/dev_guide/developing_modules_documenting.html#fields


Would you be happy that if a module's ANSIBLE_METADATA changes that all open issues & PRs get updated with the new labels?

**Comment by mkrizek** [comment]
Superseded by https://github.com/ansible/ansibullbot/issues/1332
