### ISSUE TITLE
Don't set labels or mention people on broken merges

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#837]
https://github.com/ansible/ansible/pull/34028 shows
* a failed rebase
* Lots of labels added
* lots of people notified

We should detect these type of cases and the bot shouldn't updates labels or `@mentions`

**Comment by pilou-** [comment]
Bot could:
- disable notifications when there are more than 10 commits (PR with more than 10 commits aren't mergeable by the bot, see #835)
- add `needs_rebase` label to these pull-request (because submitter must rebase the PR)

**Comment by dagwieers** [comment]
This is a duplicate of https://github.com/ansible/ansibullbot/issues/787

**Comment by MarkusTeufelberger** [comment]
Another one: https://github.com/ansible/ansible/pull/34264
