### ISSUE TITLE
ignored not being honored

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#840]
https://github.com/ansible/ansible/blame/devel/.github/BOTMETA.yml#L471 has
```
$modules/network/f5/:
    ignored: Etienne-Carriere mhite mryanlam perzizzle srvg wojtek0806
    maintainers: caphrim007
```

Though https://github.com/ansible/ansible/pull/34207 notified wojtek0806

**Comment by caphrim007** [comment]
here's another https://github.com/ansible/ansible/pull/34412 

Etienne-Carriere is on the ignore list but was still notified

**Comment by caphrim007** [comment]
another https://github.com/ansible/ansible/pull/34415

wojtek0806 is on the ignore list but was still notified

**Comment by caphrim007** [comment]
another https://github.com/ansible/ansible/pull/34441

mryanlam is on the ignore list but was still notified
