### ISSUE TITLE
incorrect needs_rebase

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#844]
https://github.com/ansible/ansible/pull/34684 has `needs_rebase` label when it shouldn't
```
Metadata
waiting_on: maintainer
changes_requested_by: null
needs_info: False
needs_revision: False
needs_rebase: False
merge_commits: []
mergeable_state: clean
shippable_status: success
maintainer_shipits (module maintainers): False
community_shipits (namespace maintainers): False
ansible_shipits (core team members): False
shipit_actors (maintainer or core team member): None
shipit_actors_other:
```

**Comment by gundalow** [comment]
also https://github.com/ansible/ansible/pull/34753

**Comment by jctanner** [comment]
Those two issues are now merged so I can't validate, but I think the label is coming from the mergeable_state property. Next time to find one like this, check the api data's `mergeable_state` key:

https://api.github.com/repos/ansible/ansible/pulls/####
