### ISSUE TITLE
@ansibot This issue is waiting for your response. Please respond or the issue will be closed.

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#856]
`@ansibot This issue is waiting for your response. Please respond or the issue will be closed.`

https://github.com/ansible/ansible/issues/29490#issuecomment-361970925

**Comment by jctanner** [comment]
@mkrizek can you try to fix this one? You'll need to validate the issuewrapper.submitter is returning the original submitter instead of ansibot (it was auto-migrated).

**Comment by gundalow** [comment]
https://github.com/ansible/ansible/issues/29486#issuecomment-361970965
https://github.com/ansible/ansible/issues/29730#issuecomment-361970756
+ lots others

**Comment by mkrizek** [comment]
So I went through these https://github.com/ansible/ansible/issues?q=%22%40ansibot+Please+respond+or+the+issue+will+be+closed%22+in%3Acomments+is%3Aopen [1] by hand and put needs info back, we'll let ansibot handle them with #858. I am going to close this, please re-open if there's anything else that needs to be done.

[1]
https://github.com/ansible/ansible/issues/30090
https://github.com/ansible/ansible/issues/29734
https://github.com/ansible/ansible/issues/29730
https://github.com/ansible/ansible/issues/29727
https://github.com/ansible/ansible/issues/29486
