### ISSUE TITLE
refactor code that builds the repoiterator into a shared function

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#891]
https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/ansible.py#L1512

_collect_repos is useful to the awx folks also, so let's make it shared in default triager or put it into a utility

**Comment by mkrizek** [comment]
`collect_repos` is now in `DefaultTriager`.

Fixed in https://github.com/ansible/ansibullbot/pull/1574.
