### ISSUE TITLE
Reduce (network) notifications 

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#894]
Network may or may not be a special case here

I'm wondering if component `network(ing)` should not be used to look up maintainers. 

For example, the following notification all/moat network maintainers. 
A) https://github.com/ansible/ansible/issues/38776
`All network modules for all device families. E.g., ios, ios-xr, nxos, eos, etc...`

B) https://github.com/ansible/ansible/issues/36871#issuecomment-381334296
`supported network modules`

**Discussion**
1) Treat `network` as a special case and ignore it for the purposes of notifications.
2) Should topic labels still be added (`f5`, `nxos`)?

**Comment by bigmstone** [comment]
Would you still have a mechanism for notifying all maintainers in certain cercumstances? In both your examples it’s something I would want to track, if not contribute to.

I’ve no idea how noisy notifications get from core networking requests but it hasn’t been overwhelming yet (take with a grain of salt as I’ve only been on that list ~1 week). So I can see how this would be desirable if you’re constantly getting unnecessary notifications. I’m personally okay with the odd false positive if it keeps me in the loop of broader networking issues. 

Side note: that “Files identified in the description” comment on ansible/ansible#36871 is out of hand. 😂

**Comment by gundalow** [comment]
@bigmstone I'm not sure how much of an issue it is. Though I've had a couple of people mention it to me in the last week.  The "Files identified" is as a result of component: `supported network modules`
What's happening is
Ansibullbot is treating `supported`, `network` and `modules` as keywords to look up. As their is a directory called `network` (`lib/ansible/modules/network/`) Ansibullbot currently looks up the maintainer of every file under that directory.

**Comment by gundalow** [comment]
No seen this issue since, it's actually fairly rare that someone triggers a notification for all network platforms
