### ISSUE TITLE
Bot incorrectly removing ci_verified label

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#895]
The bot keeps removing the `ci_verified` label from https://github.com/ansible/ansible/pull/39373 after I manually add it, even though no new CI runs have been performed. This is likely due to having Zuul status on the PR.

**Comment by jctanner** [comment]
The only way I can explain this is that maybe the bot used the zuul ci status once and believed the PR passed all tests? It doesn't seem possible based on the codeblock but it's really hard to tell without sufficient logs or a reproducible situation. 

https://github.com/ansible/ansibullbot/pull/898 adds a persistent store for all historical statuses the bot knows about. That will at least confirm or debunk my suspicion if this ever happens again.

**Comment by mattclay** [comment]
Here's another PR the bot is removing the label from: https://github.com/ansible/ansible/pull/43945

**Comment by mattclay** [comment]
Another PR with the same issue: https://github.com/ansible/ansible/pull/44443
