### ISSUE TITLE
extra pings

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#897]
https://github.com/ansible/ansible/issues/36915

Akasurde was already involved. He didn't need to be pinged.

**Comment by Akasurde** [comment]
@jctanner I am not sure about the context here but additional pings are due to this change - https://github.com/ansible/ansible/pull/39113 (I modified bot meta as team_vmware was not getting ping for vmware_inventory issues/PRs)

**Comment by jctanner** [comment]
Should be fixed by https://github.com/ansible/ansible/pull/40272
