### ISSUE TITLE
Reduce long lists of files down to globs in component comment.

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#903]
https://github.com/ansible/ansible/issues/36871#issuecomment-379059517

Most of that could have been foo/bar/*.

**Comment by jctanner** [comment]
@mkrizek this one might interest you also if you are messing with the matching engine

**Comment by Akasurde** [comment]
Example - https://github.com/ansible/ansible/issues/63127

**Comment by gundalow** [comment]
I don't believe this happens anymore, so closing
