### ISSUE TITLE
Cancel Shippable runs when adding the merge_commit label

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#920]
When the bot adds the merge_commit label to a PR it should also cancel the Shippable run if it has not already completed. This will avoid wasting CI resources since CI will run again once the merge commits have been corrected.

**Comment by jctanner** [comment]
So this is going to require an addition to the AnsibleActions class in triagers/ansible.py. In my mind, it would look something like ...

```
class AnsibleActions(DefaultActions):
    def __init__(self):
        super(AnsibleActions, self).__init__()
        self.close_migrated = False
        self.rebuild = False
        # new property ...
        self.cancel = False
```

Then the cancel will kill the running job(s) for the PR.
