### ISSUE TITLE
Link to module-checklist and optional amazon/GUIDELINES.md

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#93]
http://docs.ansible.com/ansible/developing_modules.html#module-checklist https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/GUIDELINES.md

**Comment by gundalow** [comment]
It appears that if a PR fails to build initially we don't link to the module-checklist

as (not) shown here

https://github.com/ansible/ansible-modules-extras/pull/1987

**Comment by jctanner** [comment]
@gundalow can you give a little more context please?

**Comment by gundalow** [comment]
Ignore this till the docs as better
