### ISSUE TITLE
If a "shipit" label is removed, do not re-add it

### ISSUE THREAD

**Issue by gregdek** [ansible/ansibullbot#97]
4:15 PM <•bcoca> or just detect that shipit was removed AFTER it had been triggered set by comment
4:15 PM <•bcoca> ^ bot should be smart enough to look at ticket timeline
4:15 PM <•gregdek> Bot does have some of those smarts. We just need to set the logic.
4:15 PM <•gregdek> Should be doable to say:
4:15 PM <•bcoca> and only act when 'non acted on trigger' appears
4:16 PM <•gregdek> "If any core team comment comes after any shipit, unflag shipit".
4:16 PM <•gregdek> Would that rule work?
4:16 PM <•bcoca> no, i would say if anyone removed 'previous shipit' don't do shipit
4:16 PM <•bcoca> unless new comments
4:16 PM <•gregdek> But we have no way of detecting if "someone removed shipit" currently.
4:17 PM <•bcoca> you can see ticket action history
4:17 PM <•gregdek> resmo can you look at action timeline as well as comment timeline?
4:17 PM <•gregdek> I was never able to, but maybe you can
4:17 PM <•bcoca>  #1 creatd, #2 shpiit comment #3 bot sets shipit label #4 someone removes label, #2 should not trigger another 'shipit' label
4:17 PM <•gregdek> yes, i understand
4:17 PM <alikins> anyone got pointers to example pr's that show the wrong behavior?  I'm interested in fixing it
4:18 PM <•gregdek> That presumes we can accurately detect #4

**Comment by bcoca** [comment]
improperly removed python3 label:
https://github.com/ansible/ansible-modules-extras/pull/2367

**Comment by bcoca** [comment]
added pending action, though nothing was requested from user https://github.com/ansible/ansible-modules-core/pull/3870

**Comment by alikins** [comment]
> added pending action, though nothing was requested from user ansible/ansible-modules-core#3870

The pending action label and the "maintainer unknown ping @gregdek @resmo @robynbergeron."  is a result of the bot noticing that that module has no maintainer. 

See https://github.com/ansible/ansibullbot/pull/101

**Comment by gregdek** [comment]
These are separate issues, would be good to address them as such in future; this PR is just for "shipit" relabeling.

Re: labels being removed, the bot removes all "unknown" labels; we can just add them to the "ignore" list. I will add Python3.

Re: pending action, @alikins is correct.

**Comment by alikins** [comment]
For reference, all the current labels for

core:
```
['P1',
 'P2',
 'P3',
 'P4',
 'P5',
 'aws',
 'azure',
 'backport',
 'bug_report',
 'bugfix_pull_request',
 'cloud',
 'community_review',
 'core_review',
 'digital_ocean', 
 'docs_pull_request',
 'docs_report',
 'easyfix',
 'feature_idea',
 'feature_pull_request',
 'gce',
 'in progress',
 'needs_info',
 'needs_rebase',
 'needs_revision',
 'networking',
 'new_plugin',
 'owner_pr',
 'pending_action',
 'python3', 
 'shipit',
 'vmware',
 'windows',
 'work_in_progress']
```

extras:
```
['P1',
 'P2',
 'P3',
 'P4',
 'P5',
 'aws',
 'backport',
 'bug_report',
 'bugfix_pull_request',
 'cloud',
 'community_review',
 'core_review',
 'digital_ocean',
 'docs_pull_request',
 'docs_report',
 'easyfix',
 'feature_idea',
 'feature_pull_request',
 'gce',
 'in progress',
 'needs_info',
 'needs_rebase',
 'needs_revision',
 'networking',
 'new_plugin',
 'owner_pr',
 'pending_action',
 'python3',
 'related_prs',
 'shipit',
 'windows',
 'work_in_progress']
```
