### ISSUE TITLE
Bot starts and then cancels CI run on PRs

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#982]
The bot appears to be starting [1], and then cancelling, CI runs on PRs. Here are a few examples:

https://app.shippable.com/github/ansible/ansible/runs/74702 (ansible/ansible#39877)
https://app.shippable.com/github/ansible/ansible/runs/74699 (ansible/ansible#40489)
https://app.shippable.com/github/ansible/ansible/runs/74700 (ansible/ansible#40489)
https://app.shippable.com/github/ansible/ansible/runs/74693 (ansible/ansible#41010)
https://app.shippable.com/github/ansible/ansible/runs/74690 (ansible/ansible#41115)
https://app.shippable.com/github/ansible/ansible/runs/74689 (ansible/ansible#41115)

In some cases it seems the bot then started them again:

https://app.shippable.com/github/ansible/ansible/runs/74694 (ansible/ansible#41010)
https://app.shippable.com/github/ansible/ansible/runs/74691 (ansible/ansible#41115)

It's possible the cancellation could be due to another CI run being started on the PR. However, even if that were the case, I'm not sure why the bot is starting CI runs on these PRs.

[1] Based on the username associated with starting the jobs in the Shippable UI. It's possible this is inaccurate, as Shippable is known to switch users for API calls when it encounters errors (rate limiting or otherwise) attempting to access the ansible/ansible repo.

**Comment by mkrizek** [comment]
@mattclay with https://github.com/ansible/ansibullbot/pull/987 is this still an issue?

**Comment by mattclay** [comment]
I haven't noticed this in a while, although it doesn't mean it isn't occurring. I'm fine closing this.

**Comment by mkrizek** [comment]
If you see this happening again please open a new issue or re-open this one, thanks!
