### ISSUE TITLE
WIP label is stuck after unWIPing the title

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansibullbot#996]
The above is a bug (observed @ https://github.com/ansible/ansible/pull/44099). The bot should unlabel `WIP` from the PR.

**Comment by mkrizek** [comment]
Looking at this, it seems to me that the bot didn't get a change to process the issue to remove the label. The `WIP` was removed from the title at 2:18 PM and the `WIP` label was removed manually at 5:10 PM. I'd say we should probably close this and re-open if we see the issue again. At first glance, I don't see anything that should cause this in the code.

**Comment by webknjaz** [comment]
But it's 3 hours between events. The bot runs every 10 minutes. So it's about 7-8 chances to remove the label. Any logs of trying to remove it?

**Comment by webknjaz** [comment]
Now this happened to `needs_triage` (at least it feels related): https://github.com/ansible/ansible/issues/44748#issuecomment-416591714

`-label needs_triage` has no effect.

**Comment by webknjaz** [comment]
I think the bot needs more logging of its interaction with GitHub.

**Comment by mkrizek** [comment]
> But it's 3 hours between events. The bot runs every 10 minutes. So it's about 7-8 chances to remove the label. Any logs of trying to remove it?

I still think this is not an issue. There are 3700+ open issues and 1500+ open PRs. Sometimes the bot goes through a good amount of them and it could take some time. Also, networks.

Agreed on better logging, that could be always improved.

cc @jctanner

**Comment by jctanner** [comment]
"more logging" is ill defined. There's nothing in this issue that describes what data would have been useful to understand why the bot didn't do an action. The problem appears to be more about training than technology.
